### ISSUE TITLE
Adguard blocks internet connectivity for some iOS apps on M1 Mac

### ISSUE THREAD

**Issue by jeroenvannieuwenhove** [AdguardTeam/AdguardForMac#820] opened 2021-02-02 09:42 UTC
I've noticed with several apps that internet connectivity seems to be blocked when Adguard's "Automatically Filter Applications" (set to Network Extension) is enabled on the latest nightly and public releases. Disabling this allows internet connectivity again.

### Steps to reproduce

1. Download https://apps.apple.com/is/app/rúv/id1438344717 (as an example) on an M1 Mac
2. Open the app with Adguard enabled.

### Expected behavior
It should load a list with all available programs to watch.

<img width="1158" alt="Screenshot 2021-02-02 at 09 40 22" src="https://user-images.githubusercontent.com/4172255/106581357-ad018a80-653a-11eb-95a6-cfc77e05e979.png">

### Actual behavior
Nothing shows up.

<img width="1158" alt="Screenshot 2021-02-02 at 09 39 54" src="https://user-images.githubusercontent.com/4172255/106581290-9ce9ab00-653a-11eb-88dc-3d4853c4c2a2.png">

### Non-working apps
So far I have found that these below don't work with Adguard's application filtering enabled.

RÚV - https://apps.apple.com/is/app/rúv/id1438344717
TV Time - https://apps.apple.com/us/app/tv-time-track-shows-movies/id431065232
Vivino - https://itunes.apple.com/app/id414461255?mt=8

### Sysinfo

MacBook Air M1 running Big Sur 11.2. Verified this on 11.0.1 and 11.1 as well. No other filtering apps are in use.

**Comment by Chinaski1** [comment] 2021-02-02 09:49
Hello there! @jeroenvannieuwenhove 

Could you please provide a complete list of applications so we can check the issue?

**Comment by jeroenvannieuwenhove** [comment] 2021-02-02 10:02
So far I have found that these below don't work with Adguard's application filtering enabled.

- RÚV - https://apps.apple.com/is/app/rúv/id1438344717
- TV Time - https://apps.apple.com/us/app/tv-time-track-shows-movies/id431065232
- Vivino - https://itunes.apple.com/app/id414461255?mt=8

**Comment by Chinaski1** [comment] 2021-02-02 14:43
@jeroenvannieuwenhove 
These applications are not filtered by AdGuard by default, did you add them to the list of manually filtered applications?

**Comment by jeroenvannieuwenhove** [comment] 2021-02-02 14:49
> @jeroenvannieuwenhove
> These applications are not filtered by AdGuard by default, did you add them to the list of manually filtered applications?

Everything, or almost everything, on my Adguard is default. I did not add them to the list (double-checked now as well). I also just downloaded Vivino without doing anything in Adguard and it did not work after a fresh install.

**Comment by Chinaski1** [comment] 2021-02-03 10:45
The issue was reproduced only on **RÚV** 
**TV Time** and **Vivino** work even though I added them to the filter list.
Thank you for the information, we will try to look into the causes of this situation in the near future.

**Comment by sfionov** [comment] 2021-02-16 12:10
This app seems to be created in Flutter. So this is duplicate of #795.

Here is the part of Console log.
```
default	15:05:08.760960+0300	Runner	TCP Conn 0x600000c01600 starting SSL negotiation
default	15:05:08.771502+0300	Runner	[VERBOSE-2:shell.cc(210)] Dart Unhandled Exception: Bad state: Future already completed, stack trace: #0      _AsyncCompleter.complete (dart:async/future_impl.dart:43)
#1      _NativeSocket.startConnect.<anonymous closure>.connectNext.<anonymous closure> (dart:io-patch/socket_patch.dart:682)
#2      _NativeSocket.issueWriteEvent.issue (dart:io-patch/socket_patch.dart:1102)
#3      _NativeSocket.issueWriteEvent (dart:io-patch/socket_patch.dart:1109)
#4      _NativeSocket.multiplex (dart:io-patch/socket_patch.dart:1130)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168)
```

**Comment by ameshkov** [comment] 2021-03-04 09:54
This is fixed in dartio so eventually it will be fixed in Flutter-based apps. Not sure if Apple will be doing anything about this.

**Comment by ameshkov** [comment] 2021-03-22 08:33
A bit more info on this here: https://github.com/AdguardTeam/AdguardForMac/issues/795#issuecomment-803866324

**Closed by ameshkov** 2021-03-22 08:33 UTC
Labels: Bug, Medium, P3: Medium, Resolution: Won't Fix, Status: Resolved, Version: CoreLibs v1.8
