### ISSUE TITLE
Adguard on Mac disable http2

### ISSUE THREAD

**Issue by voanhduy1512** [AdguardTeam/AdguardForMac#107] opened 2016-07-04 07:45 UTC
Hi,

When i enable adguard on mac, Chrome stops using http2 and fallback to http1 (on Gmail or Facebook). I check with uBlock and don't see this problem.

Can you guys take a look on it?

**Comment by ameshkov** [comment] 2016-07-04 08:43
We should add H2 support to AG first, currently it does not yet supports it.

**Comment by ameshkov** [comment] 2018-01-10 09:28
Duplicate of #232

**Closed by ameshkov** 2018-01-10 09:28 UTC
Labels: Duplicate
