### ISSUE TITLE
Use custom adguard: scheme for adding userscripts

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForMac#577] opened 2019-08-12 10:04 UTC
@ameshkov commented on [Thu Jul 11 2019](https://github.com/AdguardTeam/AdguardForWindows/issues/2838)

1. Update CoreLibs to convert userscript links to use `adguard:` scheme
2. Intercept these links and offer to install a userscript
3. No more intercept `.user.js` on the network level

**Comment by Stillness-2** [comment] 2019-10-07 11:49
Duplicate of #578

**Closed by Stillness-2** 2019-10-07 11:49 UTC
Labels: Duplicate, Enhancement, P3: Medium
