### ISSUE TITLE
No allow button in system preferences

### ISSUE THREAD

**Issue by inazarab** [AdguardTeam/AdguardForMac#461] opened 2019-04-12 18:52 UTC
### Steps to reproduce

1. Open the Adgaurd for mac app.
2. Click on the link to allow system permission.
3.
4.

### Expected behavior
 The app should open a pop-up screen with a link requesting the systems permission. The link should open system preferences and show a button to allow permission.

### Actual behavior
 When clicking the link to opens system preferences there is no allow button.

<details><summary>Screenshot:</summary>

<img width="790" alt="Screen Shot 2019-04-12 at 2 40 53 PM" src="https://user-images.githubusercontent.com/25354384/56059275-b7351200-5d31-11e9-80c5-d24eb0bde9d3.png">

<img width="660" alt="Screen Shot 2019-04-12 at 2 41 01 PM" src="https://user-images.githubusercontent.com/25354384/56059285-bdc38980-5d31-11e9-8c19-58ab2e37ab01.png">

</details>

### Your environment

* Environment name and version: (e.g. Chrome 59):
* Any specific potentially conflicting software installed: (e.g. antiviruses, firewalls, traffic counters, cleaners)

**Comment by ameshkov** [comment] 2019-04-12 20:23
What version of Mac OS and AdGuard are you using?

**Comment by krechcigl** [comment] 2019-04-12 20:26
I just wanted to comment that I am having the same exact problem. Mac Mojave 10.14.5 Beta (18F108f). Using Adguard 2.0.0 beta

**Comment by ameshkov** [comment] 2019-04-12 20:27
This is a duplicate of #350 then.

The issue is resolved in the nightly version.

**Closed by ameshkov** 2019-04-12 20:27 UTC
Labels: Duplicate

**Comment by krechcigl** [comment] 2019-04-12 21:28
I can confirm that the nightly fixed the issue.
