### ISSUE TITLE
Update Icon

### ISSUE THREAD

**Issue by AtomicCoding** [AdguardTeam/AdguardForMac#184] opened 2017-03-17 01:34 UTC
**Yes, I know...this isn't quite an issue, however, this isn't open source, so I can't create a Pull Request. ** 
Ok so, using Image2Icon, I have changed the Windows Adguard icon to be a compatible ICNS file using the online PNG. It can be found at: https://mega.nz/#!Mlo2hLrC!kYer6HM-DPmSM9egn8oHpoePn8Q_DtMneATulyGNnas

**Comment by ameshkov** [comment] 2017-03-20 10:36
Heh, we actually should use the new logo:
![chrome_extension_icon_128x128](https://cloud.githubusercontent.com/assets/5947035/24096303/350bed5a-0d72-11e7-84a9-d55797a86ec9.png)


@Stillness-2 please let me know when you're ready for this task, I'll provide you with the new logo sources.

**Comment by AtomicCoding** [comment] 2017-03-20 23:05
Yeah, that icon is actually much nicer. But as long as it's more modern than the current one, I'm happy!

**Comment by ameshkov** [comment] 2017-08-10 11:14
Duplicate of https://github.com/AdguardTeam/AdguardForMac/issues/202

Will be done in the next beta.

**Closed by ameshkov** 2017-08-10 11:14 UTC
Labels: UI
