### ISSUE TITLE
Diacritical Symbols Issue

### ISSUE THREAD

**Issue by lolka4toli** [AdguardTeam/AdguardForMac#813] opened 2021-01-18 09:02 UTC
### Steps to reproduce
1. Send a message using diacritical symbols in the Facebook Messenger on the M1-device.

### Expected behavior
A normal message will be sent.

### Actual behavior
All words with diacritical symbols will be replaced with "?".

<details><summary>Screenshot:</summary>

![Capture d’écran 2020-12-13 à 23 19](https://user-images.githubusercontent.com/70013567/104893062-020e9f80-5984-11eb-80e4-ea2a747fe608.jpg)

</details>

### Customer ID 
3082296

### Your environment

* Environment name and version: Apple Silicon (M1) device + Facebook Messenger 83.5
* Any specific potentially conflicting software installed: CleanMyMac X

### Additional
Sometimes there is no connection in this app using AdGuard. Facebook Messenger in not filtered.

**Comment by sfionov** [comment] 2021-01-18 10:40
Messenger app crashes on ADP (A12Z Bionic processor) device, so I can't check it.

**Comment by evasilis** [comment] 2021-01-18 11:12
This is the list of filters in use:

![Screen Shot 2021-01-18 at 13 08 58](https://user-images.githubusercontent.com/74712901/104908196-c4634400-598e-11eb-8b0d-29396da0952d.png)

**Comment by TheHasagi** [comment] 2021-01-18 12:16
@evasilis 

Even when the messenger is filtered or not by Adguard it's working fine on my side, I can write in French and symbols are not changed by (?). Can't say for sure it's related to AdGuard.

**Comment by evasilis** [comment] 2021-01-18 18:57
Thanks for your reply

French and symbols rely of the Latin script. it is only when I switch to the Greek one that the problem appears. I thought that the problem is related to adguard as when I turn it off I cannot reproduce the problem/error.

Regards

**Comment by unsequoia** [comment] 2021-01-20 15:30
Hi all,

Here is a link to a video illustrating my problem.
[https://www.youtube.com/watch?v=rc4yvV8L7E8](url)
Thanks in advance and good luck :)

Regards,
Ced

**Comment by evasilis** [comment] 2021-01-20 17:35
That is exactly the problem!

**Comment by Chinaski1** [comment] 2021-01-27 14:33
@evasilis @unsequoia 
Unfortunately, the issue is not reproduced on my side.
Could you try disabling all filters, stealth-mode settings, and extensions (While leaving modules enabled) and check if the issue still persists?

**Comment by evasilis** [comment] 2021-02-03 09:28
This issue seems to have been resolved with the installation of macos 11.2

**Comment by Chinaski1** [comment] 2021-02-03 09:35
Glad to hear it :)

**Closed** 2021-02-03 09:35 UTC
