### ISSUE TITLE
Login item missing icon image until first launch

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardForMac#1414] opened 2024-04-24 09:51 UTC
### AdGuard version

2.14.0.1591 nightly (CL-1.14.53, DNS-2.5.19)

### Browser version

Version 17.5 (19618.2.10.11.4)

### OS version

14.5 Beta (23F5064f)

### What filters do you have enabled?

AdGuard Base filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter

### Issue Details

Steps to reproduce:
1. Install AdGuard for Mac

### Expected Behavior

Login item has an icon image

### Actual Behavior

Login item doesn't have an icon image

### Screenshots

<details><summary>Screenshot 1:</summary>

<img width="471" alt="Screenshot 2024-04-24 at 7 32 19 PM" src="https://github.com/AdguardTeam/AdguardForMac/assets/149243371/6928378c-b5f1-4edb-820f-c05fc3aed2af">

</details>

**Comment by PavelParkhomenko** [comment] 2024-04-25 09:57
Hello! Thank you for providing the information. Normally, the item "Adguard Software Limited" should not be present on the list. We haven't made any changes to this module recently, so it's possible that the issue is related to changes in macOS. However, we'll investigate further to identify the cause.

**Comment by PavelParkhomenko** [comment] 2024-05-22 07:03
Hello! Could you please verify if the issue persists with the latest version of AdGuard?

**Comment by PavelParkhomenko** [comment] 2024-05-28 06:45
Since we haven't received any feedback and are unable to reproduce the issue on our end, we will close the issue for now. Please don't hesitate to reopen it if you have any new information.

**Closed** 2024-05-28 06:46 UTC
Labels: Bug, Priority: P4
