### ISSUE TITLE
AdGuard activation - Sign in with Apple not working

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardForMac#1418] opened 2024-04-26 02:41 UTC
### Issue Details

When using the Sign in with Apple method, it will not complete, continuing in an endless loop of opening the Sign in with Apple page, confirming the login, then back to the Sign in with Apple page.

macOS: 14.5 Beta (23F5064f)
Safari: Version 17.5 (19618.2.10.11.4)
AdGuard for Mac: Version 2.14.0.1594 nightly

### Proposed solution

Complete the Sign in with Apple feature, then be taken back to the app.

**Comment by Aydinv13** [comment] 2024-04-26 11:59
@jslawler-gh 

Could you please record a short video so we can see what it looks like?

**Comment by ghost** [comment] 2024-04-26 12:19
@Aydinv13 - Emailed to apple@adguard.com.

**Comment by Aydinv13** [comment] 2024-04-26 15:54
@jslawler-gh can't find your message. Could you resend it please?

**Comment by ghost** [comment] 2024-04-26 15:56
@Aydinv13 forwarded a second time to apple@adguard.com.

The subject is the same name as this issue.

**Comment by Aydinv13** [comment] 2024-04-26 17:32
@jslawler-gh e-mailed you personally.

**Comment by ghost** [comment] 2024-04-26 17:40
@Aydinv13 I've replied with the attachment.
Failing that I'm in both the AdGuard Telegram and AdGuard Slack.

**Comment by Aydinv13** [comment] 2024-04-27 08:40
Does a cache reset or reboot help? Does it happen only with Apple login? Could you also check it with different browser please.

**Comment by oo-rbiiix** [comment] 2024-04-28 10:00
I have same issue. Adguard for mac app is sign out and impossible to activate. Login with apple ID is looped, Activation code enter is not reacting. Tried beta, nightly, previous versions. All the same. Probably it could be related with newest mac os beta. Maybe it blocks the activation process ? dont know 
![Screenshot_2024-04-28 11 47 36_ZNf9hj](https://github.com/AdguardTeam/AdguardForMac/assets/168338589/2a541db3-b997-4827-b9d6-010af2ee0b42)
![CleanShot 2024-04-28 at 11 45 17@2x](https://github.com/AdguardTeam/AdguardForMac/assets/168338589/d676ef3f-99d9-4003-bd8c-1f43d417cb05)
![CleanShot 2024-04-28 at 11 44 37@2x](https://github.com/AdguardTeam/AdguardForMac/assets/168338589/11b27241-d261-465a-8805-1c5a5172be60)
![CleanShot 2024-04-28 at 11 43 59@2x](https://github.com/AdguardTeam/AdguardForMac/assets/168338589/6d0664e7-76b5-47a8-b189-2561ae2dcc28)
![CleanShot 2024-04-28 at 11 43 31@2x](https://github.com/AdguardTeam/AdguardForMac/assets/168338589/2a9c452f-436d-4fd0-b3dc-7112db150c76)

**Comment by ghost** [comment] 2024-04-29 08:40
@Aydinv13 It works in Google Chrome.
It seems that the social login does not finish its login, forwarding to the 2FA aspect of the AdGuard login on Safari.

**Comment by Aydinv13** [comment] 2024-05-02 09:13
@oo-rbiiix your problem is related to the recent bug in Sonoma beta 14.5 https://github.com/AdguardTeam/AdguardForMac/issues/1410#issuecomment-2089844512

**Comment by Aydinv13** [comment] 2024-05-02 10:46
@jslawler-gh 

Can you check if authorization via Apple (with Safari) works in another app not related to AdGuard? It can be a website as well.
What if you update to a new beta version of Sonoma?

**Comment by ghost** [comment] 2024-05-02 11:01
@Aydinv13 

I'm able to use "Login with Apple" with Cloudflare.
I'm on the latest dev beta, and I can't login to AdGuard's website with "Login with Apple", or the app.

**Comment by Aydinv13** [comment] 2024-05-02 13:46
@jslawler-gh could you tell me which option is selected in your Settings for Safari browser in `General -> Safari opens with`?

<details><summary>Example</summary>

<img width="775" alt="up85_jkhuj" src="https://github.com/AdguardTeam/AdguardForMac/assets/73467237/5e5ff7fb-62b3-4f23-98fa-6a8fff79ad1d">
</details>

**Comment by ghost** [comment] 2024-05-03 01:41
@Aydinv13 

<img width="948" alt="Screenshot 2024-05-03 at 11 41 12 AM" src="https://github.com/AdguardTeam/AdguardForMac/assets/149243371/ed7da60b-3af6-4c95-ac65-fc8a379a705d">

**Comment by Aydinv13** [comment] 2024-05-06 13:29
@jslawler-gh I can reproduce it only with incognito mode, are you not using it in some way?

**Comment by ghost** [comment] 2024-05-06 14:19
@Aydinv13, that brings something to mind.
The feature "Use advanced tracking and fingerprinting protection" by default is set to private windows only, but I use it for all browsing.

<img width="948" alt="Screenshot 2024-05-06 at 23 33 57" src="https://github.com/AdguardTeam/AdguardForMac/assets/149243371/1c5b2eba-cae9-47eb-be63-e92b1274bf32">

It seems that this is preventing the sign-in with Apple feature, completing, then moving on to the 2FA auth AdGuard page, or completing the login.

The location for Apple's link tracking protection details can be found here: `/private/var/folders/[random]/[random]/C/com.apple.WebPrivacy`. I imagine something in there might be a giveaway as to why it's not completing.

<img width="1300" alt="Screenshot 2024-05-07 at 00 05 57" src="https://github.com/AdguardTeam/AdguardForMac/assets/149243371/f50e2ed7-5569-4255-ada7-3e912b3865b5">

**Comment by Aydinv13** [comment] 2024-05-13 09:24
As further work will be done on the web's side, I am closing this issue. As a temporary solution, set the value `to private windows only` to `Use advanced tracking and fingerprinting protection` in Safari.

**Closed by Aydinv13** 2024-05-13 09:24 UTC
Labels: Priority: P4
