### ISSUE TITLE
VMware Fusion compatibility bug

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardForMac#188] opened 2017-03-27 17:10 UTC
The problem comes up when you run a website inside of a VM and open the website on a host machine using hostname. The error that's shown is:

>Safari Can't Connect to the Server. Safari can't open the page <url> because Safari can't connect to the server <servername>.

and the guest machine's IP is 192.168.42.152 as it's NATTED. 

It does work normally if you restart Adguard.

Original thread:
https://forum.adguard.com/index.php?threads/20262/

**Comment by ameshkov** [comment] 2017-03-28 22:07
I suppose this is due to how we check if IP is reachable or now, it should be easy to reproduce

**Comment by ameshkov** [comment] 2017-03-28 22:08
I've assigned this issue to @vozersky , however, we first need to get an instruction on how to collect kernel-level logs as user-level won't help us find the culprit.

**Comment by Stillness-2** [comment] 2017-05-23 12:00
Adguard debug version with kext debugging 

https://www.dropbox.com/s/z9jrbwuit8qq7g1/Adguard_kext_dbg.zip?dl=1

**Comment by TheHasagi** [comment] 2019-07-08 09:45
Unable to reproduce it anymore.

**Closed by TheHasagi** 2019-07-08 09:45 UTC
Labels: Bug, Cannot reproduce, Compatibility
