### ISSUE TITLE
[Catalina] AdGuard Icon not visible

### ISSUE THREAD

**Issue by iDjay** [AdguardTeam/AdguardForMac#611] opened 2019-10-08 08:08 UTC
AdGuard Icon is not visible in macOS Catalina.
Video attached.

[Bildschirmvideo aufnehmen 2019-10-08 um 10.12.08.mov.zip](https://github.com/AdguardTeam/AdguardForMac/files/3701384/Bildschirmvideo.aufnehmen.2019-10-08.um.10.12.08.mov.zip)

**Comment by zzebrum** [comment] 2019-10-08 08:21
closed as a duplicate of #527

**Closed by zzebrum** 2019-10-08 08:21 UTC
