### ISSUE TITLE
Ads not blocked in Safari on macOS Sequoia with iCloud Private Relay enabled

### ISSUE THREAD

**Issue by PavelParkhomenko** [AdguardTeam/AdguardForMac#1467] opened 2024-08-23 09:36 UTC
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

AdGuard for macOS v2.15.1.1731

### Browser version

Safari 18.0

### OS version

macOS Sequoia beta (build 24A5327a) 

### Which DNS server do you use?

AdGuard DNS

### DNS protocol

None

### Support ticket ID

938104

### Issue Details

Steps to reproduce:
1. Enable AdGuard protection in the AdGuard app
2. Enable iCloud Private Relay in system settings
3. Open the Safari browser and visit the AdGuard test page

### Expected Behavior

The AdGuard test page should confirm that the AdGuard Ad Blocker is active. Ads should be blocked on other pages in Safari.

### Actual Behavior

The AdGuard test page indicates that the AdGuard Ad Blocker is not running. Ads are not blocked on other pages in Safari.

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

### Additional Information

Ad blocking functions correctly in other browsers, such as Chrome.

**Comment by BrianHao** [comment] 2024-09-17 12:40
Issue still exists as of 09/17 on the official public release of macOS Sequoia

**Comment by sfionov** [comment] 2024-09-17 14:16
@BrianHao Can you please specify, the problem happens only in first minutes after starting protection, or even after several minutes after?

**Comment by siddiqq** [comment] 2024-09-17 14:46
same here , still not working on the official release, several minutes after starting

**Comment by sfionov** [comment] 2024-09-17 14:50
@siddiqq
Can you please try to delete `icloud.com` from `network.extension.exclude.domains` advanced setting?

**Comment by ojizero** [comment] 2024-09-17 15:53
> @siddiqq Can you please try to delete `icloud.com` from `network.extension.exclude.domains` advanced setting?

@sfionov facing the same issue here, it seems to improve blocking a bit, but still shows assets that should blocked (not sure how to quantify how much it helped though or if it's a placebo of sorts).

Attaching some screenshots here with and without private relay both having deleted `icloud.com` from `network.extension.exclude.domains` advanced setting.

<details>
<summary>Here's with PrivateRelay enabled</summary>

<img width="1895" alt="image" src="https://github.com/user-attachments/assets/881da10b-2cef-43de-85fb-0ffa36c94460">

</details>

<details>
<summary>And with PrivateRelay disabled</summary>

<img width="2205" alt="image" src="https://github.com/user-attachments/assets/14ac8544-c259-4de4-a4c0-002f852811cd">

</details>

**Comment by BrianHao** [comment] 2024-09-17 16:10
Same experience here - 

> @BrianHao Can you please specify, the problem happens only in first minutes after starting protection, or even after several minutes after?

Same experience as the above - I am still seeing ads at all times, and have:
- deleted icloud.com from network.extension.exclude.domains advanced setting.
- Make sure I have the latest Adguard updates / filters
- Hard restarted Adguard, Safari, macOS

**Comment by legion-heresy** [comment] 2024-09-18 06:02
As a workaround, changing AdGuard to run as an Automatic Proxy instead of a Network Extension resolved this for me. Go to AdGuard's settings > Network > General > Filtering Mode to change it.

**Comment by kaznovac** [comment] 2024-09-20 11:59
Have the same issue
Pausing the Private Relay seems to help
Switching to Automatic Proxy mode blocks the ads but introduces network instability (timeouts while connecting and in the middle of transfer)

**Comment by baslia** [comment] 2024-09-20 18:54
Hey, I have the same issue since the public release of Sequoia

**Comment by sfionov** [comment] 2024-09-26 06:51
Main issue: https://github.com/AdguardTeam/CoreLibs/issues/1914

Reported to Apple: https://developer.apple.com/forums/thread/764531

Workaround: To turn off either iCloud Private Relay or Firewall

**Comment by baslia** [comment] 2024-09-29 04:45
> Main issue: [AdguardTeam/CoreLibs#1914](https://github.com/AdguardTeam/CoreLibs/issues/1914)
> 
> Reported to Apple: https://developer.apple.com/forums/thread/764531
> 
> Workaround: To turn off either iCloud Private Relay or Firewall

Thank you, is there a way to upvote the issue reported to apple ?

**Comment by sfionov** [comment] 2024-10-04 13:11
In our tests filtering is working again on macOS 15.1 beta even with Firewall on.

I'm not sure if fix is present in 15.0.1 released today.

**Comment by baslia** [comment] 2024-10-05 07:35
I just tried on 15.0.1 and the issue is still there, I guess we would need to deactivate icloud private relay until macOS 15.1 is released

**Comment by siddiqq** [comment] 2024-10-09 14:42
> In our tests filtering is working again on macOS 15.1 beta even with Firewall on.
> 
> I'm not sure if fix is present in 15.0.1 released today.

@sfionov I'm on 15.1 beta latest build 24B5070a, and it's still not working for me. I turned Private Relay on and it was blocking ads for maybe 5-10 minutes, then sure enough ads started leaking back into Youtube, etc. :(

**Comment by baslia** [comment] 2024-10-28 18:58
Hey, I am on macOS 15.1 and I can confirm that the issue is still there.
Edit: I actually found a solution online:
AdGuard Settings > Network > Filtering Mode > Automatic Proxy

**Comment by Aydinv13** [comment] 2024-10-30 14:49
@baslia @siddiqq @kaznovac could you try the latest [Nightly](https://agrd.io/mac_nightly) build?

**Comment by siddiqq** [comment] 2024-11-13 05:03
> @baslia @siddiqq @kaznovac could you try the latest [Nightly](https://agrd.io/mac_nightly) build?

Tried it last night, so far so good! Seems to have fixed it

**Comment by baslia** [comment] 2024-11-13 05:58
> > @baslia @siddiqq @kaznovac could you try the latest [Nightly](https://agrd.io/mac_nightly) build?
> 
> Tried it last night, so far so good! Seems to have fixed it

Did you use the nightly build ?
Edit: the nightly build update was available for me today, and it seems that the problem is solved.
Edit2: After less than a day, the Ads started to show up again, so I had to deactivate Private Cloud.

**Comment by siddiqq** [comment] 2024-11-30 08:24
> > > @baslia @siddiqq @kaznovac could you try the latest [Nightly](https://agrd.io/mac_nightly) build?
> > 
> > 
> > Tried it last night, so far so good! Seems to have fixed it
> 
> Did you use the nightly build ? Edit: the nightly build update was available for me today, and it seems that the problem is solved. Edit2: After less than a day, the Ads started to show up again, so I had to deactivate Private Cloud.

reporting back.. similarly it stopped working again. Had to also deactivate Private Relay again. I doubt this is ever going to get fixed

**Comment by lothar-cell** [comment] 2024-11-30 12:46
Yeah, it goes on and off, and I really hope it will be fixed.

**Comment by Quentin-Gigon** [comment] 2024-12-01 17:14
> Hey, I am on macOS 15.1 and I can confirm that the issue is still there. Edit: I actually found a solution online: AdGuard Settings > Network > Filtering Mode > Automatic Proxy

This worked, thanks! @baslia

**Comment by lothar-cell** [comment] 2024-12-01 17:18
Doesn't sound very reliable: 
<img width="513" alt="Screenshot 2024-12-01 at 18 17 24" src="https://github.com/user-attachments/assets/d74c441a-4a5b-4fb6-9020-915f8b0835f0">

**Comment by lothar-cell** [comment] 2024-12-01 19:29
Even with Private Relay switched off, Adguard is busted on Sequoia with Safari, websites like YouTube, Amazon, Aliexpress are slow, images load forever or not at all and textboxes have latency activating, and with Adguard switched off behaviour is back to normal, Firefox has no issues. It's a mess really and I'm not sure the team is aware of it at all.

**Comment by Aydinv13** [comment] 2024-12-02 09:33
There's an update from Apple - macOS 15.2 Beta 4 that probably fixes the bug.

**Closed as completed** 2024-12-19 13:30 UTC
Labels: Bug, Resolution: Done, Status: Closed, Priority: P1, Version: AdGuard v2.16

**Comment by baslia** [comment] 2024-12-19 14:28
This works as of now, on Macos 15.2
