### ISSUE TITLE
No HTTPS browser connectivity after 2.5.0.902 (CL-1.7.119) update

### ISSUE THREAD

**Issue by TheWojtek** [AdguardTeam/AdguardForMac#755] opened 2020-10-13 13:42 UTC
### Steps to reproduce

1. Update to 2.5.0.902
2. Use a browser (Safari 14, Chrome 86.0.4240.75, Firefox 80.0.1 tested) to navigate to any HTTPS site

### Expected behavior
Site should display

### Actual behavior
No site displays, with following errors:

Safari: Safari Can’t Open The Page www.onet.pl Because Safari Can’t Establish A Secure Connection To The Server
Chrome: This site can’t be reached The connection was reset. ERR_CONNECTION_RESET
Firefox: Secure Connection Failed - An error occurred during a connection to www.onet.pl. PR_CONNECT_RESET_ERROR

**Note: non-secure (HTTP) sites open correctly.**

**Note2: excluded HTTPS sites open correctly.**

System log entries:

error	16:12:55.270905+0200	Adguard	(AAPLogFilteringEventsConverter[0x600001573e80] defineListener) Can't find log object in the pool of an active log objects:[(0x0x600003c58ea0) ID=1000023, reqID=200030, info="tcp://www.onet.pl:443", rule="" appName="Safari"]
default	16:12:55.272209+0200	com.adguard.mac.adguard.network-extension	(0): Flow 2038788220 is connecting
default	16:12:55.272474+0200	com.adguard.mac.adguard.network-extension	(2038788220): New flow: NEFlow type = stream, app = com.apple.Safari, name = , address = 104.22.3.106, port = 443, filter_id = , interface = en2
default	16:12:55.272887+0200	com.adguard.mac.adguard.network-extension	[Extension com.adguard.mac.adguard]: Calling handleNewFlow with TCP com.apple.Safari[{length = 20, bytes = 0x45ccca24af75fb0cffde9e9f9e3dbc436831f25c}] remote: 104.22.3.106:443
default	16:12:55.273179+0200	com.adguard.mac.adguard.network-extension	filteredApps: (
    "com.polysuite.polybrowser",
    "com.brave.Browser.helper.renderer",
    "org.mozilla.SeaMonkey",
    "com.maxthon.mac.Maxthon",
    "org.mozilla.nightly",
    "com.google.Chrome.canary",
    "com.operasoftware.OperaNext",
    "com.brave.Browser.helper.plugin",
    "com.operasoftware.OperaDeveloper",
    "com.flashpeak.Slimjet",
    "jp.co.fenrir.sleipnir",
    "com.AlphaOmegaSoftware.DesktopWebBrowser",
    "com.vivaldi.Vivaldi",
    "com.apple.Safari",
    "org.Runecats.Roccat",
    "org.chromium.Chromium.helper",
    "org.mozilla.firefoxdeveloperedition",
    "com.apple.SafariTechnologyPreview",
    "com.opera.Neon",
    "com.brave.Browser.nightly.helper",
    "com.operasoftware.Opera",
    "org.mozilla.waterfox",
    "com.catalinagroup.Citrio",
    "org.chromium.Chromium",
    "com.microsoft.Outlook",
    "com.microsoft.edgemac",
    "com.flashpeak.SlimBoat",
    "com.brave.Browser.helper",
    "de.icab.iCab",
    "com.microsoft.edgemac.helper",
    "ru.yandex.desktop.yandex-browser.helper
default	16:12:55.273355+0200	com.adguard.mac.adguard.network-extension	object: com.apple.Safari
default	16:12:55.300086+0200	com.adguard.mac.adguard.network-extension	(2038788220): Closing reads (suppressing SHUT_WR), closed by plugin
default	16:12:55.300167+0200	com.adguard.mac.adguard.network-extension	(2038788220): Closing writes, sending SHUT_RD
default	16:12:55.300270+0200	com.adguard.mac.adguard.network-extension	(2038788220): Destroying, client tx 0, client rx 156, kernel rx 156, kernel tx 0

### Environment

* Little Snitch reports both AdGuard and adguard_service attempting to connect both are allowed all outgoing connections.

MacOS Catalina 10.15.7

**Comment by PrissyPixie** [comment] 2020-10-13 17:00
I have this issue too in both Safari and Firefox after updating Adguard today.

**Comment by Chinaski1** [comment] 2020-10-13 17:05
Hello there!

Sorry for the inconvenience.
Please try to reset the AdGuard settings - this should help you to restore the service.

Let us know should you have any additional questions.

**Comment by ddriese** [comment] 2020-10-16 07:32
Having the same issue in the latest Big Sur beta, resetting AdGuard settings did not help - had to disable AdGuard altogether at this point until there's an update.

**Comment by Chinaski1** [comment] 2020-10-16 09:06
@ddriese 

Hello, unfortunately, the latest BigSur update breaks AdGuard in the Safari browser.
We are currently working on fixing this situation.

**Comment by locussss** [comment] 2020-10-16 17:19
Switching to Automatic Proxy is for the moment the best solution.....

**Comment by Chinaski1** [comment] 2020-10-20 16:04
Hello, dear users!

Please, try to update the latest Nightly version of AdGuard for MAC (agrd.io/mac_nightly).
There are reasons to believe that this update fixes the issue you have specified.

And let us the result, please!

**Comment by ddriese** [comment] 2020-10-20 21:13
Seems to be working here.  Connectivity is back and no more infinite loading on YouTube videos like previous releases.  Thank you!  👍

**Comment by Chinaski1** [comment] 2020-10-21 08:40
I am closing the task because the issue has been resolved and this fix will be included in the next patch 2.5.1.
Please let me know if you have any additional questions.

**Comment by Eugene-Savenko** [comment] 2020-10-27 10:14
Another set of logs here: 1649641 (helpdesk ID).

**Comment by vozersky** [comment] 2020-10-27 15:48
@Chinaski1 @Eugene-Savenko still can be reproduced with the latest nightly?

**Comment by Chinaski1** [comment] 2020-10-27 15:55
@Eugene-Savenko 
A version of AdGuard app(ID: 1649641): Application version: 2.5.0.902 release (CL-1.7.119)
Looks like he should install the latest Nightly.

**Comment by nohli** [comment] 2020-10-29 13:03
For about two weeks I can't use AdGuard any more. Even just enabling it, without any filters, breaks the internet...could you hotfix this into an update, since this issue was closed eight days ago and this bug breaks the internet? Or do you have a beta version?
I have bought an AdGuard license and am using the macOS Big Sur beta (which works very well), but don't feel comfortable installing a nightly build of AdGuard just to make it work...if I did install the nightly build, would it then get normal stable updates in the future?
This is the third time that after an iOS or macOS update AdGuard breaks the internet...and the updates apparently take a lot of time. For iOS it took a couple of months, probably because a new UI was on the way, and then finally there was an update from 2.1.2 to 4.0.1. This was especially weird, because in the meantime, the non-paid version with in-app purchases got the following updates: 3.0, 3.0.1, 3.0.2, 3.1, 3.1.1, 3.1.2, 3.1.3, 4.1.4, 4.0 - so it kind of looks like, once you buy the app, you're not as important as users using the free app and have subscriptions, which they are able to cancel?
I wouldn't complain for open source software, but AdGuard is software that people have already paid money for.

**Comment by Chinaski1** [comment] 2020-10-29 14:09
Hello, @nohli 

Now I will try to clarify the situation.
Version 2.5.0 was aimed precisely at improving compatibility with the new operating system.
Used earlier old framework named Kernel Extensions — was declared as deprecated.
The main change was the addition of System extension support on BigSur.
Unfortunately, as a replacement for Kernel Extensions, Network Extensions aren't around for long yet (they first appeared in this role in macOS 10.15). They are still being actively developed by Apple, so there is a significant amount of various issues associated with them. 
All the more reason to keep in mind that BigSur is still in beta version, there are regular updates that in theory may contain changes that disrupt the operation of our application.
And in order to support our users who decided to upgrade to BigSur, we try to find solutions and fix the issues in the shortest possible time. Therefore, Nightly versions are released almost every day. Stable versions of AdGuard don't need critical updates at this moment. Considerable development effort is instead being put into making AdGuard work with Big Sur, while Apple is constantly changing the Big Sur beta and introducing new bugs, which our developers are forced to work around.

As for your specific issue:
- First, you need to install the Nightly(agrd.io/mac_nightly) version and check if the issue persists.

If the issue still there:
- Here's what preferably to do:

1. Menu -> Gear -> Advanced -> Logging level -> Debug;
2. Reproduce the issue (and remember the exact time when it happened);
3. Menu -> Advanced -> Export Logs and System Info...;
4. Send the archive to **`apple@adguard.com`** and mention this issue number in the subject.

**Closed** 2020-10-30 12:25 UTC
Labels: Bug, P2: High, Resolution: Fixed, Status: Resolved
