### ISSUE TITLE
When reporting a website in Safari: open in a new tab instead of a window, or respect the default user option

### ISSUE THREAD

**Issue by planet0** [AdguardTeam/AdguardForMac#1127] opened 2022-09-01 06:57 UTC
Usually, new links open in new tabs. When reporting a website in the AdGuard extension, it always opens in a brand new window, which makes reporting for me a little more tedious on a single screen.

Could we either change it so it opens the reporting page in a new tab, or respect the user setting in Safari for what is set under 'Open pages in tabs instead of windows'?

<img width="399" alt="image" src="https://user-images.githubusercontent.com/65204836/187851342-247a5dd3-28ea-439d-a3e4-174af857853c.png">

**Comment by Aydinv13** [comment] 2022-09-01 08:26
Duplicate of https://github.com/AdguardTeam/AdguardForMac/issues/1100

**Closed by Aydinv13** 2022-09-01 08:26 UTC

**Comment by planet0** [comment] 2022-09-01 09:27
@Aydinv13 Whoops, my mistake!
