### ISSUE TITLE
Adguard-tcpkill is not code-signed

### ISSUE THREAD

**Issue by Rediwed** [AdguardTeam/AdguardForMac#269] opened 2017-12-28 14:10 UTC
Adguard-tcpkill is not codesigned (while Adguard itself is). Is it possible to fix this to prevent malicious code from being injected?

http://i.imgur.com/LjAysrF.png

**Comment by altokarev** [comment] 2017-12-28 14:13
Duplicate of #268

**Closed by altokarev** 2017-12-28 14:13 UTC
