### ISSUE TITLE
AdGuard breaks Flutter on macOS Big Sur

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForMac#808] opened 2020-12-24 06:05 UTC
### Steps to reproduce
1. Install Flutter (https://flutter.dev)
2. Try to execute any command in Flutter (e.g. clean Xcode workspace)
3. If protection is enabled, Flutter will throw an unhandled exception

### Actual behavior
Flutter throws an unhandled exception when attempting to execute any command while AdGuard is enabled.

<details><summary>Screenshot:</summary>

<img width="910" alt="flutter1" src="https://user-images.githubusercontent.com/33634917/103065200-a76d6800-45be-11eb-935b-7c37f91d1a32.png">
<img width="554" alt="flutter2" src="https://user-images.githubusercontent.com/33634917/103065204-a9372b80-45be-11eb-91ba-739cfac7c794.png">

</details>

### Customer ID & debug logs
3091733

### Your environment
* Environment name and version: (e.g. Chrome 59): Flutter 1.20.4 (Stable) + Dart 2.9.2, AdGuard 2.5.1 (SetApp build), macOS Big Sur version 11.1 (build 20C69)

**Comment by Chinaski1** [comment] 2020-12-24 08:45
Duplicate of https://github.com/AdguardTeam/AdguardForMac/issues/795

**Closed** 2020-12-24 08:45 UTC
Labels: Duplicate
