### ISSUE TITLE
Missing 'Protect from DPI' when reporting issue to AdguardFilters

### ISSUE THREAD

**Issue by planet0** [AdguardTeam/AdguardForMac#1068] opened 2022-05-14 10:14 UTC
When reporting an issue to AdguardFilters, the new 'Protect from DPI' option in the Stealth Mode settings do not appear in the report.

Application version 2.8.1.1140 release (CL-1.9.62, DNS-1.7.22)

### Steps to reproduce

1. Enable Protect from DPI
2. Report a website via Safari Extension

### Expected behavior
All enabled stealth mode options show

### Actual behavior
Protect from DPI does not appear

**Comment by Chinaski1** [comment] 2022-05-16 09:39
Looks like this task is duplicate of https://github.com/AdguardTeam/AdguardForMac/issues/1067

So I close it.

**Closed** 2022-05-16 09:40 UTC
