### ISSUE TITLE
[2.0.2.548 nightly] AdGuard stopped filtering completely

### ISSUE THREAD

**Issue by planet0** [AdguardTeam/AdguardForMac#507] opened 2019-05-28 11:06 UTC
I was heavily using Chrome and noticed that I started seeing Ad results in Google, which was strange. I searched a few terms and ads continued to appear. Then, my Spotify started playing ads.

Nothing was being filtered anymore. I quit and relaunched AdGuard. Same issues. I'm not really sure what happened... but I've exported the logs.

### Steps to reproduce

1. Hard to reproduce, but heavily use Chrome and Spotify

### Expected behavior

AdGuard continues to work

### Actual behavior

AdGuard has stopped working completely.

<details><summary>Screenshot:</summary>
<img width="803" alt="Screen Shot 2019-05-28 at 8 54 02 pm" src="https://user-images.githubusercontent.com/46271764/58473431-eab9e780-818b-11e9-9700-0ab06babf3bf.png">
<img width="809" alt="Screen Shot 2019-05-28 at 8 54 27 pm" src="https://user-images.githubusercontent.com/46271764/58473432-eab9e780-818b-11e9-9501-17acabb0fcb6.png">

</details>

### Customer ID 

2190205

### Your environment

* Environment name and version: (e.g. Chrome 59): Chrome Version 74.0.3729.169 (Official Build) (64-bit)
* Any specific potentially conflicting software installed: (e.g. antiviruses, firewalls, traffic counters, cleaners): None

**Comment by planet0** [comment] 2019-05-28 11:12
I just restarted macOS, and the issue is still occuring. AdGuard seems to now be permanently not working. I'm going to try to uninstall AdGuard altogether and install the latest stable build.

**Comment by planet0** [comment] 2019-05-28 11:20
Yes, can confirm that going back to current stable (1.5.14) has resolved the issue. Not sure what happened with 2.0.2.548 nightly.

Not sure if the Customer ID has the same logs as exporting it from the program - if not, happy to provide them if needed.

**Comment by ameshkov** [comment] 2019-05-28 11:30
The issue is the new version of QUIC that Google started using recently.

It will be resolved in today's update.

**Closed by ameshkov** 2019-05-28 11:30 UTC

**Comment by planet0** [comment] 2019-05-28 11:37
Thank you @ameshkov!
