### ISSUE TITLE
Adguard compatibility with Opera built-in VPN 

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardForMac#130] opened 2016-09-22 13:06 UTC
Adguard's HTTPS filtering breaks VPN connection for SurfEasy VPN (Opera built-in)

**Comment by vozersky** [comment] 2016-09-22 13:08
same with [Adguard for Windows](https://github.com/AdguardTeam/AdguardForWindows/issues/1174)

**Comment by ameshkov** [comment] 2016-09-28 15:52
The issue is resolved in Opera Dev.

**Comment by ameshkov** [comment] 2016-09-28 16:02
Ah, I am wrong, the issue is still here.

**Comment by ameshkov** [comment] 2016-09-28 16:02
@Stillness-2 contact me when you are ready to work on this issue.

**Comment by Stillness-2** [comment] 2016-11-21 17:47
#123

**Closed** 2016-11-21 17:51 UTC
Labels: Network-related
