### ISSUE TITLE
No internet with custom DNS in dnscrypt

### ISSUE THREAD

**Issue by michael1900** [AdguardTeam/AdguardForMac#528] opened 2019-06-12 13:29 UTC
Hi, on osx 10.14.5, using last nightly adguard at writing moment i have this problem from at least 2-3 months:

If i set a **custom dns** in dnscrypt .toml file and adguard is ON i have no more internet connection!
If i leave  **default dns** in dnscrypt .toml file and adguard is ON internet connection works well without problems.

This is with Safari, Chrome, etc.., i tried all possible combinations but the problem is Adguard.
I have many purchased license and this bug it's really tedious and it needs to be fixed because it's almost impossible to use now dnscrypt and adguard together like before.

Thanks

**Comment by ameshkov** [comment] 2019-06-13 09:47
> If i set a custom dns in dnscrypt .toml file and adguard is ON i have no more internet connection!

Any custom DNS server or some specific ones?

**Comment by michael1900** [comment] 2019-06-13 11:52
I tried with many custom dns and always the same problem, try for example with dns from dnscrypt.
It's really impossible to try with all honestly, but for all those i tried the problem is there.

**Comment by ameshkov** [comment] 2019-06-13 12:41
What DNS resolver is used by default?
How exactly have you configured dnscrypt-proxy? Is there an app or have you done it manually?

**Comment by michael1900** [comment] 2019-06-13 17:06
These are used by default: 
server_names = ['scaleway-fr', 'google', 'yandex', 'cloudflare']

All manually.

**Comment by ameshkov** [comment] 2019-06-14 10:19
We tried as well, but for some reason, we cannot reproduce the issue.

To troubleshoot this issue, we need to get the app logs.

Here's what we need you to do:

1. Menu -> Advanced -> Logging level -> Debug
2. Reproduce the issue (and remember the exact time when it happened).
3. Menu -> Advanced -> Export Logs and System Info...
4. Send the archive to `apple@adguard.com` and mention this issue number in the subject

**Comment by michael1900** [comment] 2019-06-14 12:59
Done now. Hoping...

**Comment by ameshkov** [comment] 2019-06-14 13:04
Hmm, I see nothing in the inbox. Could you please re-send it to `am at adguard.com`?

**Comment by michael1900** [comment] 2019-06-14 13:08
Done.

**Comment by ameshkov** [comment] 2019-06-14 14:26
@michael1900 thank you!

@Stillness-2 logs are in the private nextcloud

**Comment by michael1900** [comment] 2019-06-15 15:16
Ok, i try to explain. I am on OSX, i installed dnscrypt with brew. To manage all dnscrypt stuff i don't use third-party app, but all is managed manually with terminal and editing the .toml file in etc folder. Simply, no other stuff.

Now, i like to use dnscrypt server from this amazing vpn: https://github.com/cryptostorm

What to do to try and see no internet connection? 
Simple: use this their custom .toml file: https://raw.githubusercontent.com/cryptostorm/cstorm_deepDNS/master/dnscrypt-proxy.toml
Install last Adguard nighlty (but for me problem starts months ago), install last dnscrypt from terminal with brew, replace the default .toml file with the above cryptostorm .toml file and ... in my case there is no more internet connection working.

Now, if i close Adguard, i mean close it from Activity Manager, magically ALL internet connection now working again.

Thanks for help

**Comment by ameshkov** [comment] 2019-06-17 10:06
@michael1900 I figured what's wrong.

There's a bug in the current version -- it prevents UDP connections to port 443 system-wide. This will be fixed in the next update.

Meanwhile, the temporary solution would be to add the following rules to your user filter:
```
@@81.17.31.34:443$network
@@128.127.104.108:443$network
@@213.163.64.208:443$network
@@185.107.80.84:443$network
@@185.117.118.20:443$network
@@5.133.8.187:443$network
@@185.212.169.139:443$network
@@185.94.193.234:443$network
@@212.129.46.32:443$network
@@195.154.40.48:443$network
@@109.71.42.228:443$network
@@27.255.77.56:443$network
@@5.254.96.195:443$network
@@178.175.139.211:443$network
@@109.248.149.133:443$network
@@82.163.72.123:443$network
@@84.16.240.43:443$network
@@89.163.214.174:443$network
@@162.221.207.228:443$network
@@167.114.84.132:443$network
@@173.234.159.235:443$network
@@173.234.56.115:443$network
@@104.238.195.139:443$network
@@64.120.5.251:443$network
@@198.7.58.227:443$network
@@209.58.147.36:443$network
@@64.42.181.227:443$network
@@155.254.29.113:443$network
@@23.19.67.116:443$network
@@104.255.175.2:443$network
```

**Comment by michael1900** [comment] 2019-06-19 21:08
Got it, thanks ;)

**Comment by ameshkov** [comment] 2019-06-20 09:13
It seems my temporary solution wouldn't work:( you need to wait till the next week when we publish the fix to nightly channel.

**Comment by michael1900** [comment] 2019-06-20 11:12
I ll wait.

**Comment by Stillness-2** [comment] 2019-06-25 09:05
@michael1900 Check please last nightly version http://agrd.io/mac_nightly

**Comment by michael1900** [comment] 2019-06-26 10:25
Fixed! Now i can use cryptostorm dns w/o problems, finally 👍

**Closed** 2019-07-22 09:53 UTC
Labels: Bug, P3: Medium
