### ISSUE TITLE
Is there a way to use native DNS OS provided DNS, similarly to AdGuard for iOS?

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardForMac#1279] opened 2023-08-05 01:42 UTC
I've often found that the when it comes to AdGuard for Mac that it can be a bit troublesome when using other network filtering applications, which is an also an issue I had on iOS with various VPN requiring applications.

What I have found quite useful in AdGuard for iOS is being able to use native OS provided DNS mode, which allows iOS to handle the DNS, and AdGuard to handle which DNS server gets used.

<details>

<summary>AdGuard for iOS Native DNS</summary>

![image](https://github.com/AdguardTeam/AdguardForMac/assets/95468948/51050bbb-b0b4-4883-b787-6d75614d5cd7)
![image](https://github.com/AdguardTeam/AdguardForMac/assets/95468948/5853d792-9e58-4aae-90f4-70c0f3fbfaa6)

</details>

At the moment I am using a combination of AdGuard for Safari and a configuration profile for DNS (AdGuard Personal DNS), but would rather use AdGuard for Mac if there is a native DNS mode somewhere I am not seeing.

1. Is there an option to use native DNS in AdGuard for Mac as well, or am I limited to having AdGuard use a proxy?
2. If there isn't an option to use native DNS, can this be a feature request to have a similar feature set to AdGuard for IOS?

**Comment by Aydinv13** [comment] 2023-08-08 15:17
@jslawler Hello there!

Seems that it's a duplicate of [this](https://github.com/AdguardTeam/AdguardForMac/issues/1074) issue.

**Closed as completed** 2023-08-08 15:18 UTC
Labels: Resolution: Duplicate, Status: Closed, Priority: P4
