### ISSUE TITLE
Wi-Fi exceptions like iOS App

### ISSUE THREAD

**Issue by vincentbls** [AdguardTeam/AdguardForMac#1201] opened 2023-02-23 12:41 UTC
### Issue Details

Wi-Fi exceptions in iOS app can exclude particular Wi-Fi networks from DNS protection : why not in Mac app ? For users of AdGuard Home for example.
![network_settings_en](https://user-images.githubusercontent.com/10372975/220908336-90da4da4-8b99-4772-9295-f4e86746c6f4.jpeg)

**Comment by Aydinv13** [comment] 2023-02-28 09:01
@vincentbls Hi there!

It's already planned for v3.0. Duplicate of https://github.com/AdguardTeam/AdguardForMac/issues/901

**Closed by Aydinv13** 2023-02-28 09:01 UTC
