### ISSUE TITLE
AdGuard causing an issue with Adobe Creative Cloud Libraries not loading. 

### ISSUE THREAD

**Issue by markjgriffin** [AdguardTeam/AdguardForMac#839] opened 2021-02-22 16:00 UTC
### Steps to reproduce

1. Launch any Adobe App like Photoshop
2. Open the Creative Cloud Libraries panel
3. Error on accessing Libraries appears
4. Turn off AdGuard - set to not load on start-up, reboot, Adobe Libraries appear as normal.

### Expected behavior
Libraries should appear

### Actual behavior
Error in Adobe libraries panel

<details><summary>Screenshot:</summary>

</details>

### Your environment

* Environment name and version: 
* MacPro 2019 running macOS BigSur 11.2.1 
* Any specific potentially conflicting software installed: (e.g. antiviruses, firewalls, traffic counters, cleaners)
* No

**Comment by Chinaski1** [comment] 2021-02-24 11:06
Hello!

To troubleshoot this issue, we need to get the app logs.

Here's what we need you to do:

1. Menu -> Gear -> Advanced -> Logging level -> Debug;
2. Reproduce the issue (and remember the exact time when it happened);
3. Menu -> Advanced -> Export Logs and System Info...;
4. Send the archive to **`apple@adguard.com`** and mention this issue number in the subject.

Could you be more specific about when the issue started to reproduce?
Maybe you noticed the problem after an OS update or an update of the AdGuard application?
Usually, this behavior has been observed when using third-party antivirus or VPN services on your Mac, as well as Little Snitch.
You can also try switching to the auto-proxy mode and see if the Adobe libraries can be accessed. (AdGuad -> Network -> Select mode -> Auto-proxy).

**Comment by markjgriffin** [comment] 2021-02-24 12:24
Will do.
Just to note that I raised the issue with Adobe and they are aware of it. They think it's an issue with a recent push of CC Library (which would coincide with the issue). I was told that they subsequently pushed a new CC Library but it didn't resolve the issue. They've subsequently asked for logs which Im providing. 

Thread is here:
https://community.adobe.com/t5/creative-cloud-services/creative-cloud-libraries-error-initialising-across-2-macs-help/td-p/11849084

**Comment by markjgriffin** [comment] 2021-02-24 12:39
Will do.
Just to note that I raised the issue with Adobe and they are aware of it. They think it's an issue with a recent push of CC Library (which would coincide with the issue). I was told that they subsequently pushed a new CC Library.

Not using another AV or VPN or LS.

Logs emailed just now.

**Comment by markjgriffin** [comment] 2021-02-24 12:40
Logs attached.

Just to note that I raised the issue with Adobe and they are aware of it. They think it's an issue with a recent push of CC Library (which would coincide with the issue). I was told that they subsequently pushed a new CC Library but it didn't resolve the issue. They've subsequently asked for logs which Im providing.

Thread is here:
https://community.adobe.com/t5/creative-cloud-services/creative-cloud-libraries-error-initialising-across-2-macs-help/td-p/11849084

Not using another AV or VPN or LS.


Regards, 
-- 

Mark Griffin
Director






BXG | BrandX | BXS | BXH
The Studio, 37 Dawson Street, Dublin 2. Ireland

Australia: +61 423 519 801

Mobile: +353 87 985 4567  
Office: +353 (0)1 603 4555 
Skype: m_gr1f

Website  |   Facebook   |   LinkedIn 


Disclaimer: This email and any files transmitted with it are confidential and intended solely for the person or persons to whom it is addressed. If you are not one of the named addressees you should not disseminate, distribute, copy or alter this email. If you have received it in error please return it to the sender and delete it from your computer. Any views or opinions presented in this email are solely those of the author and might not represent those of BrandX Ltd.

Warning: Although BrandX Ltd has taken reasonable precautions to ensure no viruses are present in this email, we cannot accept responsibility for any loss or damage arising from the use of this email or attachments.

**Comment by markjgriffin** [comment] 2021-02-24 12:42
Sorry forgot to tell you the time…..

2021 02 at 12:34
Regards, 
-- 

Mark Griffin
Director






BXG | BrandX | BXS | BXH
The Studio, 37 Dawson Street, Dublin 2. Ireland

Australia: +61 423 519 801

Mobile: +353 87 985 4567  
Office: +353 (0)1 603 4555 
Skype: m_gr1f

Website  |   Facebook   |   LinkedIn 


Disclaimer: This email and any files transmitted with it are confidential and intended solely for the person or persons to whom it is addressed. If you are not one of the named addressees you should not disseminate, distribute, copy or alter this email. If you have received it in error please return it to the sender and delete it from your computer. Any views or opinions presented in this email are solely those of the author and might not represent those of BrandX Ltd.

Warning: Although BrandX Ltd has taken reasonable precautions to ensure no viruses are present in this email, we cannot accept responsibility for any loss or damage arising from the use of this email or attachments.

**Comment by markjgriffin** [comment] 2021-02-24 12:57
OK so...
Regarding Auto Proxy mode.
I had it set to Automatic Proxy and just now set it to use Network Extension instead. Rebooted and Adobe CC Libraries are loading now.

P.S. wasn't aware responding to your email would post all of the email contents on this thread!


![Screenshot 2021-02-24 at 12 47 37](https://user-images.githubusercontent.com/79467594/109003585-88af4e80-769f-11eb-8baf-7a6dfa5b370f.png)
![Screenshot 2021-02-24 at 12 47 42](https://user-images.githubusercontent.com/79467594/109003603-8ea52f80-769f-11eb-9922-a89f5768c178.png)

**Comment by Chinaski1** [comment] 2021-02-24 16:10
@markjgriffin 

I would like to ask you to get another pack of log files using auto-proxy mode.

Here's what we need you to do:

1. Network -> Select mode -> Auto-proxy
2. Menu -> Gear -> Advanced -> Logging level -> Debug;
3. Reproduce the issue (and remember the exact time when it happened);
4. Menu -> Advanced -> Export Logs and System Info...;
5. Send the archive to apple@adguard.com and mention this issue number in the subject.
6. Also be great if you could send in the Adobe application logs to help us find the cause of the issue.

**Comment by markjgriffin** [comment] 2021-02-24 16:33
Done and sent. 
FYI neither network filter or auto proxy working anymore. If I quite AG CC Libraries become available immediately.

**Comment by Chinaski1** [comment] 2021-02-24 16:53
@markjgriffin 

Thank you for the information provided.
Developers are working to find a solution to the issue.

**Comment by ngorskikh** [comment] 2021-02-25 13:41
I've banged my head against this problem for a while until it occurred to me to check something, and alas: it seems that Creative Cloud doesn't seem to work with _any_ HTTP proxy, not just AdGuard in autoproxy mode. I think this issue should be reported to Adobe :)

**Comment by markjgriffin** [comment] 2021-02-25 13:50
OK… I have done.

It seems to be working today with the filtering mode set to Network Extension. Haven’t tried flipping it back to Auto Proxy yet :-)

Thanks for your help!

**Comment by markjgriffin** [comment] 2021-02-26 12:08
FYI ....It seems that Adobe Pushed an updated CC Library version and this resolved it. All works now :-)

**Comment by Chinaski1** [comment] 2021-02-26 12:12
Oh... that's great news :)
So I close this task, if the issue still reproduces reopen it again.

**Closed** 2021-02-26 12:12 UTC
Labels: Bug, P3: Medium, Resolution: Won't Fix, Status: Resolved
