### ISSUE TITLE
Adguard blocks everything (!)

### ISSUE THREAD

**Issue by Gluon137** [AdguardTeam/AdguardForMac#1027] opened 2022-01-06 12:16 UTC
### Steps to reproduce

1. Turn on Adguard
2. Open any Website
3. Can't open website

If I turn off the HTTPS-Protocol-Filterning, the websites open, but no adware is filtered

### Expected behavior

The website should load
### Actual behavior

The website cannot be opend

<details><summary>Screenshot:</summary>

<img width="1371" alt="image" src="https://user-images.githubusercontent.com/65108924/148381198-6cbd3c18-53c1-4883-b387-18f287fb6177.png">

</details>

### Customer ID 

Customer ID 568346
Mac Montary 12.0.1 (21A559)
Safari Version 15.1 (17612.2.9.1.20)
Adguard Anwendungsversion 2.7.0.1094 release (CL-1.8.276, DNS-1.6.72)

### Your environment

* Environment name and version: (e.g. Chrome 59):
* Any specific potentially conflicting software installed: (e.g. antiviruses, firewalls, traffic counters, cleaners)
No firewall, no antivirus, nothing

**Comment by Chinaski1** [comment] 2022-01-10 08:33
Hello!

You seem to have a problem with your AdGuard security certificate:

1. Open Keychain access.
2. Find AdGuard CA and open it.
3. Check is it marked "Always trust"?

If the certificate is marked as "Always trusted" but the issue is still present, then open the AdGuard settings -> Gear -> Advanced -> Reset settings 

This move will generate a new certificate and the issue should be solved.

**Closed** 2022-01-10 08:37 UTC

**Comment by Gluon137** [comment] 2022-01-10 08:41
Thank you so much!
