### ISSUE TITLE
Does not filter new Chromium

### ISSUE THREAD

**Issue by Chinaski1** [AdguardTeam/AdguardForMac#575] opened 2019-08-08 11:31 UTC
# Steps to reproduce

1. Download and install the latest version of [Chromium](https://github.com/kramred/ungoogled-chromium-binaries/releases/download/75.0.3770.142-1/ungoogled-chromium_75.0.3770.142-1.1_macos.dmg)
2. Open the filter log 
3. Surf any site 
4. You will see that the application is not filtered

### Actual behavior

[Screenshot](https://uploads.adguard.com/Chinaskiurirl.png)

### Your environment

* Environment name and version: 75.0.3770.142 (Official Build) (64-bit)

**Comment by ameshkov** [comment] 2019-08-08 12:08
Duplicate of #574

**Closed by ameshkov** 2019-08-08 12:08 UTC
Labels: Bug
