### ISSUE TITLE
Ads not getting blocked in Firefox on silicon Macs

### ISSUE THREAD

**Issue by glomeg132** [AdguardTeam/AdguardForMac#1042] opened 2022-02-21 15:10 UTC
- Expected behavior

With AdGuard active it should block ads and trackers in Firefox.

- Actual behavior
No ads and trackers are blocked. AdGuard overview stays on 0.

The problem only exists in Firefox and not in Safari. Filters in options are selected. Also Firefox is listed in AdGuard preference under Network/Applications. AdGuard Browser Assistent is installed in Firefox. A restart of AdGuard dosn't help.

-Customer ID
580151

- Your environment
Mac OS Monterey with Firefox 97.0.1
AdGuard 2.7.0.1094

**Comment by Chinaski1** [comment] 2022-02-21 15:28
Hello there!

I think you should try to reset settings first.

If the issue still reproduce here's what we need you to do:

1. Click **AdGuard icon** in the menu bar --> Gear --> Advanced --> Logging level --> **Debug**;
2. Reproduce the issue and remember the exact time it happened;
3. Menu --> Advanced --> **Export Logs and System Info...**;
4. Send the archive to `apple@adguard.com` and mention this issue number in the subject.

**Comment by glomeg132** [comment] 2022-02-21 15:41
Reseting settings doesn't help. I exported logs and send it. I attached four screenshoots. Two from Safari without ads and two from Firefox with ads
![Firefox 1](https://user-images.githubusercontent.com/42551964/154986715-c4a88de1-e1b8-4552-b5d3-fd2f404fc812.png)
![Firefox 2](https://user-images.githubusercontent.com/42551964/154986750-4a9eb86b-89d9-4276-b7d8-2893b9634e76.png)
![Safari 1](https://user-images.githubusercontent.com/42551964/154986792-196c158b-c39c-4f6a-9abb-109d9edafd0d.png)
![Safari 2](https://user-images.githubusercontent.com/42551964/154986803-f094cb1c-983e-42c3-83df-9114dc7b93b6.png)

.

**Comment by glomeg132** [comment] 2022-02-21 16:41
I found the solution why the AdGuard counter for ads and trackers didn't count. I deactivated the DNS filter and now it's counting. I guess AdGuard only counts ads and trackers get blocked from blocklists afters DNS filtering. Probably AdGuard blocks ads and trackers in Firefox and there is only a problem with welt.de and wetter.de. These two pages show many ads in Firefox but no in Safari. Creating new rules with AdGuard Browser Assistent also doesn't help. After reloading these pages the ads are back.

**Comment by Chinaski1** [comment] 2022-02-22 09:23
Please check the security certificate in Firefox browser. Is it `AdGuard CA`?

1. Open `about:config` in the browser address bar change `security.enterprise_roots.enabled` value to `true`.
2. Restart the browser.

Any changes?

**Comment by glomeg132** [comment] 2022-02-22 11:28
I will try that later today. But I didn't activate https filtering. In the meantime I installed AdGuard for Windows on my Windows computer. Without https filtering AdGuard blocks all ads on every website. So it works perfect without https filtering on Windows. Still I don't understand what's the problem with Firefox on my Mac.

**Comment by Chinaski1** [comment] 2022-02-22 12:20
Oh, Without HTTPS filtering enabled, most ads cannot simply be filtered out. 
You can learn more about this feature in our [knowledge base](https://kb.adguard.com/en/general/https-filtering#why-does-adguard-need-to-be-able-to-filter-https).

**Comment by glomeg132** [comment] 2022-02-22 12:24
Yeah I know. But AdGuard filters ads without https filtering in Safari. It's the same computer and different results in Firefox and Safari.

**Comment by glomeg132** [comment] 2022-02-22 15:56
Just now I installed AdGuard Mac on my laptop. AdGuard blocks all kind of ads right away. The counter raises to 50 on one page. Is it possible that there is a difference between Firefox on M1 and non M1? The laptop is not an M1 Mac.

**Comment by glomeg132** [comment] 2022-02-24 05:45
Yesterday I reinstalled Firefox and AdGuard for Mac. All of the sudden it work. AdGuard start blocking ads and trackers in Firefox. But only until I changed DNS-server in AdGuard settings and selected a DNS-filterlist. I know it sounds weired but from this point Firefox started showing ads again. And even after I switched off both, DNS-server and DNS-filterlist, Firefox keep showing ads. I'am helpless.

**Comment by glomeg132** [comment] 2022-02-27 11:58
Did you checked my logs? I made a fresh install of Firefox and AdGuard. At the beginning it works perfect. Ad filters (DNS and local filters) Firefox showing ads and from this point there is no way back to normal. Safari don't has this problem.

**Comment by sfionov** [comment] 2022-02-28 08:32
@glomeg132 Unfortunately, I can't find you logs, can you please say when exactly you sent them?

**Comment by glomeg132** [comment] 2022-02-28 10:54
On 23rd February with Ticket ID 580062Sent from ProtonMail for iOS Am Mo., Feb. 28, 2022 um 09:32, Sergey Fionov ***@***.***> schrieb:  
@glomeg132 Unfortunately, I can't find you logs, can you please say when exactly you sent them?

**Comment by glomeg132** [comment] 2022-02-28 10:55
On 23rd February with Ticket ID 580062

**Comment by Chinaski1** [comment] 2022-02-28 10:55
Got it, thank you

**Comment by glomeg132** [comment] 2022-03-02 06:59
Yesterday I activated https-filtering and the ads are gone. What I do not understand is that after the installation of AdGuard ads on the same website was blocked even without https-filtering.

**Comment by glomeg132** [comment] 2022-03-02 15:38
Reseting settings in AdGuard also helps but only for a while. After couple hours all of the sudden I see some ads again. Any idea?

**Comment by glomeg132** [comment] 2022-03-03 15:50
Today I found out that the problem exist only on silicon Macs. On my intel MacBook Pro AdGuard is blocking reliable.

**Comment by Chinaski1** [comment] 2022-03-09 10:29
I checked your situation. And indeed the statistics of blocked ads and trackers remains unchanged when using DNS and disabled HTTPS filtering.
Because requests are first blocked at the DNS level (you can see it in the filtering log).
It does not matter which browser or which operating system you use.

Perhaps in the future we will add a separate counter of statistics for DNS queries.

**Comment by glomeg132** [comment] 2022-03-09 11:10
Thank you for getting back. But still I see ads with Firefox on welt.de and wetter.de. Surprisingly reseting AdGuard results in no ads on welt.de and wetter.de. But only for a while. After my computer is woken up from sleep mode, advertisements are displayed on the aforementioned pages.

**Comment by Chinaski1** [comment] 2022-03-14 13:12
Looks like your issue is related to [this task](https://github.com/AdguardTeam/AdguardForMac/issues/994). 
Seems that ad requests are active despite the sleep mode.

So I close this issue you can track the solution at the link above.

**Closed** 2022-03-14 13:13 UTC
