### ISSUE TITLE
AdGuard blocks access to Facebook.com after update of macOS

### ISSUE THREAD

**Issue by maprangsoft** [AdguardTeam/AdguardForMac#1254] opened 2023-06-23 13:40 UTC
### AdGuard version

2.10.1.1277 release

### Browser version

Microsoft Edge , Firefox

### OS version

macOS Ventura version 13.4.1

### Issue Details

Steps to reproduce:
1.
2.
3.

### Actual Behavior

adguard block [facebook](https://www.facebook.com/) after update mac os

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>
<img width="1349" alt="Screenshot 2566-06-23 at 20 33 35" src="https://github.com/AdguardTeam/AdguardForMac/assets/25447955/132cb68d-2f19-4e4d-9bd0-e5e9cf5703dd">

**Comment by Aydinv13** [comment] 2023-06-29 11:45
@maprangsoft Hi there.

Weird situation, it doesn't look like a macOS update can do that.
Is it reproducible in different network?
Could you please share your settings if it's still relevant? apple@adguard.com

**Comment by Aydinv13** [comment] 2023-07-04 12:38
@maprangsoft any update?

**Comment by Aydinv13** [comment] 2023-07-07 10:51
I'm closing this issue due to no reply. Can be reopened if relevant.

**Closed by Aydinv13** 2023-07-07 10:51 UTC
Labels: Bug, waiting for data, Priority: P4
