### ISSUE TITLE
AdGuard doesn't work with Sonoma Developer Beta 14.5 (23F5064f)

### ISSUE THREAD

**Issue by Miracle-Sakuno** [AdguardTeam/AdguardForMac#1410] opened 2024-04-23 22:20 UTC
## Updated by AdGuard team:

The latest MacOS developer beta update brought us some problems.

The [method](https://developer.apple.com/documentation/servicemanagement/smappservice/statusforlegacyplist(at:)) that detects some services running in the background seems to erroneously return `notFound`, which completely breaks AdGuard.

We are currently investigating the problem and hope to find a workaround. Further updates on the situation will also be posted here.

---

### AdGuard version

2.14.0.1588

### OS version

macOS Sonoma 14.5 Beta (23F5064f)

### Issue Details

Steps to reproduce:
1.Update to macOS Sonoma 14.5 Beta (23F5064f).
2.Open AdGuard cannot be activated and not working properly.

### Actual Behavior

Opening AdGuard on macOS Sonoma 14.5 Beta does not activate and does not work properly.
AdGuard works fine in the previous system version.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by abujesus85** [comment] 2024-04-24 02:05
Same issue here.

**Comment by Aydinv13** [comment] 2024-04-24 10:55
@abujesus85 @Miracle-Sakuno Hi there!

We are now investigating the problem. Thanks for your reports.

**Comment by longma91** [comment] 2024-04-25 01:23
I'm experiencing the same problem, I'm currently using Adguard for Safari for the time being, downloaded from the App Store, it works well, there are some limitations but it can be used as a temporary alternative until the problem is fixed. Hope this helps some

**Comment by JerryWuzi** [comment] 2024-04-25 01:38
我使用了旧版本2.12.0.1385可以使用，大家可以暂时使用旧版本，等作者修复吧

**Comment by abujesus85** [comment] 2024-04-25 03:00
> 我使用了旧版本2.12.0.1385可以使用，大家可以暂时使用旧版本，等作者修复吧

same issue with this version and build of macOS Sonoma.

**Comment by notme943** [comment] 2024-04-25 06:51
> 我使用了旧版本2.12.0.1385可以使用，大家可以暂时使用旧版本，等作者修复吧

用了这个版本，可以正常使用！

**Comment by dlesuisse** [comment] 2024-04-25 09:20
Same issue here. Unable to activate Adguard and to open it.

**Comment by zzebrum** [comment] 2024-04-25 09:47
The latest MacOS developer beta update brought us some problems.

The [method](https://developer.apple.com/documentation/servicemanagement/smappservice/statusforlegacyplist(at:)) that detects some services running in the background seems to erroneously return ‘notFound’, which completely breaks AdGuard.

We are currently investigating the problem and hope to find a workaround. Further updates on the situation will also be posted here.

[Here](https://forums.developer.apple.com/forums/thread/750685) is the thread on the Apple forum.

**Comment by Aydinv13** [comment] 2024-04-25 16:56
We've just released a new [Nightly](https://agrd.io/mac_nightly) with a workaround, so please check the build on your end.

**Comment by PMheart** [comment] 2024-04-25 17:35
> We've just released a new [Nightly](https://agrd.io/mac_nightly) with a workaround, so please check the build on your end.

Yes, this one works for me. Thanks!

**Comment by rotu** [comment] 2024-04-25 18:53
Can confirm. I encountered this on the macOS public (not developer) beta yesterday, and it appears fixed in the latest Adguard nightly

**Comment by abujesus85** [comment] 2024-04-25 19:50
> We've just released a new [Nightly](https://agrd.io/mac_nightly) with a workaround, so please check the build on your end.

I can confirm that the nightly build is working on macOS 14.5 Beta (23F5064f) again.

**Comment by nilathedragon** [comment] 2024-04-25 20:41
> We've just released a new [Nightly](https://agrd.io/mac_nightly) with a workaround, so please check the build on your end.

Working well on Version 14.5 Beta (23F5064f). Much appreciated!

**Comment by Miracle-Sakuno** [comment] 2024-04-25 23:39
> We've just released a new [Nightly](https://agrd.io/mac_nightly) with a workaround, so please check the build on your end.

2.14.0.1594 nightly runs fine on macOS 14.5 Beta (23F5064f), thanks

**Closed** 2024-04-25 23:40 UTC
Labels: Bug, Resolution: Fixed, Status: Resolved, Priority: P1, Version: AdGuard v2.14.1

**Comment by Gatewayy** [comment] 2024-04-26 05:40
Confirming that this corrects the issue on the most recent beta release build.

**Comment by TinyToon13** [comment] 2024-04-26 05:41
Also runs fine on macOS 14.5 Beta (23F5064f)

**Comment by Berovowilare** [comment] 2024-04-26 13:16
In short, with the nightly it works again.
But it is interesting AdGuard and AdGuard VPN are the only two apps which always needs an new confirmation after a macOS update. No one other does. And AdGuard was the only one which stopped working after the upgrade to the macOS beta. I guess there is a conjunction. 
But this is only my leafy observations.

**Comment by thedenethor** [comment] 2024-05-01 17:48
Look like same problem started to appear with the new 14.5 Beta (23F5074a). Nighty that fixed the problem fails with this version of MacOS.

**Comment by dlesuisse** [comment] 2024-05-01 19:12
Everything is working fine, here, with the latest nighty AdGuard version and 14.5 beta 23F5074a, on MBPro M1 Max 2021.

**Comment by thedenethor** [comment] 2024-05-01 19:41
> Everything is working fine, here, with the latest nighty AdGuard version and 14.5 beta 23F5074a, on MBPro M1 Max 2021.

Intesting, I re-installed the nightly after your comment and now its working again

**Comment by Aydinv13** [comment] 2024-05-02 07:59
>Everything is working fine, here, with the latest nighty AdGuard version and 14.5 beta 23F5074a, on MBPro M1 Max 2021.

We've received a response from Apple on [this issue](https://forums.developer.apple.com/forums/thread/750685), saying that after the changes in the recent beta, this shouldn't occur anymore, i.e. you can still use the release and beta builds of AdGuard with the new beta of macOS.
