### ISSUE TITLE
The app crashes, filtering doesn't work

### ISSUE THREAD

**Issue by jellizaveta** [AdguardTeam/AdguardForMac#1331] opened 2023-10-30 15:51 UTC
### AdGuard version

AdGuard for Mac v2.12.2.1415 release

### Browser version

Safari

### OS version

macOS 14

### Issue Details

Steps to reproduce:
Open Safari browser, website [https://www.calcalist.co.il/home/0,7340,L-8,00.html#google_vignette](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.calcalist.co.il%2Fhome%2F0%2C7340%2CL-8%2C00.html%23google_vignette)

The advertisement is displayed.

### Expected Behavior

Ads are blocked correctly.

### Actual Behavior

The app crashes, filtering doesn't work

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://cdn.adguard.info/sitereports/nz3kdm9ussgw0s4wso00kos00k84gs083yb4955co0.png?nc=1)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://cdn.adguard.info/sitereports/mw5dd0z62pwgs8g0gcssgccg4skkogkthpw7g8rruo.png?nc=1)
</details>
<details>
  <summary>Screenshot 3</summary>

  ![Screenshot 3](https://cdn.adguard.info/sitereports/2wrlcv5ow5ic4k84kk88s4s0g8844ok9vg0ryl14js.png?nc=1)
</details>

### System configuration

Information | Value
--- | ---
AdGuard product: | AdGuard for Mac v2.12.2.1415 release
System version: | macOS 14.0
Browser: | Safari
License type: | paid
Stealth mode: | disabled
DNS filtering: | server: `https://doh.opendns.com/dns-query`<br>filters: `openDNS`
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base<br/><br/><b>Other:</b><br/>Filter unblocking search ads and self-promotion<br/><br/><b>Language-specific:</b><br/>AdGuard Russian, <br/>AdGuard German, <br/>AdGuard Japanese, <br/>AdGuard Dutch, <br/>AdGuard French, <br/>EasyList Hebrew, <br/>EasyList Italy, <br/>Adblock List for Finland, <br/>Dandelion Sprout's Nordic Filters
Userscripts: | AdGuard Assistant (url: https://userscripts.adtidy.org/release/assistant/4.3/assistant.user.js)
Other extensions used: | nothing new.

### Additional Information

related issue: https://github.com/AdguardTeam/AdguardFilters/issues/164873
username: @yoelf22

**Comment by Aydinv13** [comment] 2023-10-30 16:22
@yoelf22 Hi there!

Could you please uninstall the app ([Regular](https://adguard.com/kb/adguard-for-mac/installation/#regular) and [Advanced](https://adguard.com/kb/adguard-for-mac/installation/#advanced)) then install the newest [nightly](https://agrd.io/mac_nightly) build.
Also, you can try to update your macOS to v14.1.

If you still have the same problem, please:
1) Grab the debug logs and send them to us:
<details>
<summary>Instruction</summary >

1. Click **AdGuard icon** in the menu bar --> Gear --> Advanced --> Logging --> Logging level --> **Debug**;
2. Reproduce the issue and remember the exact time it happened;
3. Menu --> Advanced --> Logging --> **Export Logs and System Info...**;
4. Send the archive to `apple@adguard.com` and mention this issue number in the subject.
</details>

2) Send the crash report when it happens. Remember the email you sent the report from (specify in your message).

**Comment by yoelf22** [comment] 2023-10-30 16:56
OK
Done.
Seems to be working now…

Let’s give it a few more days.

Thanks for your support


=================

Yoel Frischoff
tel. +972.54.626.6221
***@***.***

**Comment by Aydinv13** [comment] 2023-11-03 09:03
@yoelf22 for now I'm closing the task. If you have any issues again, feel free to report it here.

**Closed by Aydinv13** 2023-11-03 09:03 UTC
Labels: Bug, waiting for data, Priority: P4
