### ISSUE TITLE
internet connection drops, you should turn on/off to get it to work

### ISSUE THREAD

**Issue by aliafshany** [AdguardTeam/AdguardForMac#1004] opened 2021-12-05 10:34 UTC
### Steps to reproduce

it just happens on its own.

### Expected behavior
the whole connection drops
### Actual behavior
internet will gone

<details><summary>Screenshot:</summary>

i have recorded a video but because there are my personal chats on telegram i can not share it here, but i can share it via telegram or even Gdrive ( in restricted mode)

</details>
as soon as you turn off and on my internet works again, i have tested this on latest beta, release, nightly version with DNS Protection turned on ( tested on all available protocols ) and turned off
 

*Logs are deleted due to privacy reasons*

### Your environment

* Environment name and version: (e.g. Chrome 59): Mac os 12.0.1 Montery
* Any specific potentially conflicting software installed: (e.g. antiviruses, firewalls, traffic counters, cleaners)
just express vpn ( i have tested all protocols and location )

**Comment by Chinaski1** [comment] 2021-12-06 11:38
@aliafshany 

Hello!
Could you please specify the exact time at which the connection issue occurred?

**Comment by aliafshany** [comment] 2021-12-06 12:03
hello
i don't have the exact time but it is 13:35 - 13:40

does this one help you to find the report you want?

fyi, this man has the same issue https://t.me/adguard_en/151387

**Comment by Aydinv13** [comment] 2022-09-20 14:21
@aliafshany could you check if the issue is still relevant with the latest version of AdGuard and Monterey?


>fyi, this man has the same issue https://t.me/adguard_en/151387

As for this case, this man had a completely different situation related to antivirus compatibility

**Comment by aliafshany** [comment] 2022-09-20 19:17
@Aydinv13 
that's so nice of you to remember this issue and you trying to solve it after almost a year.
 i confirm that i don't have any problem with this issue. at least on big sur 11.7

**Comment by Aydinv13** [comment] 2022-09-21 09:32
@aliafshany thank you for your feedback. I'm closing the issue then.

**Closed by Aydinv13** 2022-09-21 09:32 UTC
Labels: Resolution: Cannot Reproduce, Status: Resolved
