### ISSUE TITLE
AdGuard Download Performance Issue with HTTP(s) Proxy Set to other Computer in LAN

### ISSUE THREAD

**Issue by owenzhao** [AdguardTeam/AdguardForMac#747] opened 2020-09-28 12:46 UTC
### Steps to reproduce

1. I have a Clash proxy on another computer and set in this mac with "10.0.0.114:7890", HTTP Proxy, HTTPS Proxy, Socks Proxy.
2. download iOS 14.2 beta image from developer.apple.com

### Expected behavior

When AdGuard is disable, the download speed will be over 222Mbps, when AdGuard is enabled, the download speed will be only around 10Mbps.

### Actual behavior

<details><summary>Screenshot:</summary>

</details>

### Your environment

Safari 14.0.1 (16610.2.5)
AdGuard 2.5.0.892 nightly (CL-1.7.114)
macOS Big Sur 11.0 Beta (20A5374i)

**Comment by zzebrum** [comment] 2020-10-08 17:35
@owenzhao can you reproduce the problem and collect debug log, please? And send it to apple[at]adguard[dot]com

**Comment by owenzhao** [comment] 2020-10-10 02:19
> @owenzhao can you reproduce the problem and collect debug log, please? And send it to apple[at]adguard[dot]com

Just installed latest macOS 11 Big Sur. The issue still exists. However, how to reproducing it needs more steps. 

### Preparation:

1. install the latest AdGuard. Mine is 2.5.0.900 nightly (CL-1.7.119).
2. set the lan proxy in system setting, for me, it is Wi-Fi setting, HTTP/s and Socks Proxy all set to 10.0.0.114:7890.
3. in AdGuard, set use AdGuard as HTTP proxy, with default port:3128.

You will find that the CPU usage is huge.

<img width="387" alt="huge_cpu" src="https://user-images.githubusercontent.com/2182896/95643160-f76c8080-0adf-11eb-92e9-24b2734be95d.png">

> Before "set use AdGuard as HTTP proxy", AdGuard doesn't filter anything when the HTTP Proxy is set in system. 
> After set, AdGuard filter works but the CPU usage is huge.

### Reproducing:
1. Stop and quit AdGuard. If it didn't work. Use task monitor to force quit AdGuard.
2. Open AdGuard again. Then disable AdGuard internal HTTP Proxy.
3. Download iOS device image from developer.apple.com.

> Though AdGuard HTTP Proxy is disabled. The filter still works. You may need to find why. As it didn't work before the enable and disable process.
> When filter is working, AdGuard slow down the download speed. It can be easily compared by disable AdGuard in the system menu bar icon.

1. pause download in Safari. 
2. disable AdGuard in system menu.
3. download again in Safari.

**Just send the log, the title is "adguard_logs_20201010015453".**

macOS Big Sur 11.0 Beta版(20A5384c)
Safari 14.0.1 (16610.2.6.1.6)
AdGuard 2.5.0.900 nightly (CL-1.7.119)

**Comment by sfionov** [comment] 2020-10-14 08:14
@owenzhao This seems to be not a proxy problem, but some incompatibility with AdGuard. Can you please say what you do before AdGuard starts consuming more CPU? Does this happen after visiting some site? Does closing that site helps?

**Comment by owenzhao** [comment] 2020-10-14 09:05
> @owenzhao This seems to be not a proxy problem, but some incompatibility with AdGuard. Can you please say what you do before AdGuard starts consuming more CPU? Does this happen after visiting some site? Does closing that site helps?

The CPU usage went high right after I enabled the internal HTTP proxy in AdGuard. Before that, AdGuard didn't work on filtering any ads. As it was well known that AdGuard only worked with no proxy.

I didn't go to some unusual website. the site was [macrumors.com,](macrumors.com) which I used a lot. In macOS 10.15, it didn't take CPU that much.

The high CPU usage was easy to deal with. Although the CPU usage still existed after I quit Safari, I could force quit it by using Activity Monitor.

I was more curious on the other parts.

### Why the internal HTTP Proxy worked? 
I had two HTTP Proxies, one was on System, the other was on AdGuard. When both Proxies worked together, which one went first? Or did the order unknown? Did that caused the high CPU usage?

### Why after disabled the internal HTTP Proxy, the filter still worked?
The state of the AdGuard should be the same as the internal HTTP Proxy was not set. But in fact it didn't. After enable and disable, AdGuard's filter worked but the performance  was down.

So was this a bug in AdGuard that the HTTP proxy still working even the internal HTTP proxy was set disabled. Or was that a bug on the macOS Big Sur part? Or there was other reasons?

**Comment by sfionov** [comment] 2020-10-14 12:33
1) If you just turn on HTTP proxy in AdGuard, is does nothing - it just listen on some port for connections, and this makes sense only if AdGuard is set as system HTTP proxy for HTTP+HTTPS on some device.

2) You should not set same proxy for HTTP+HTTPS and SOCKS. Proxy may be two types - HTTP proxy and SOCKS5 proxy. because usually proxy is SOCKS5 (which is set as SOCKS) or HTTP (which is set as HTTP+HTTPS). So if Clash proxy type is HTTP, then you should set HTTP+HTTPS system proxy, if it is socks, you should set SOCKS.

**Comment by sfionov** [comment] 2020-10-14 13:00
@owenzhao

I have some notes about your configuration:

1) If you just turn on "Use AdGuard as HTTP proxy" in AdGuard, it just listens on some extra port for connections, and it makes sense only if AdGuard is set as system HTTP proxy for HTTP+HTTPS on some device.
This shouldn't affect system-wide filtering in any way because it is just extra functionality.
May be checking this checkbox triggered reconfiguration of AdGuard, and behaviour had changed.

2) Generally, the same proxy should not be set for both HTTP+HTTPS and SOCKS.
Typical proxy may be two types - HTTP proxy and SOCKS5 proxy. 
HTTP proxy is set in macOS settings as system proxy for HTTP+HTTPS (Apple names them as "HTTP proxy" and "HTTPS proxy" but it is incorrect - they are better to be named "HTTP proxy for HTTP" and "HTTP proxy for HTTPS")
SOCKS5 proxy is set in macOS settings as system SOCKS5 proxy.
So it is better to use only one type of proxy (HTTP+HTTPS or SOCKS)


However, thousands of requests in the log are generated by Safari, so Safari may be somewhat broken by new filtering method. That's may be just another manifestation of Apple network library incompatibility with Apple NetworkExtensions API, which we are already reported to Apple. Let's wait for Big Sur Beta 10.

**Comment by owenzhao** [comment] 2020-10-18 04:38
> @owenzhao
> 
> I have some notes about your configuration:
> 
> 1. If you just turn on "Use AdGuard as HTTP proxy" in AdGuard, it just listens on some extra port for connections, and it makes sense only if AdGuard is set as system HTTP proxy for HTTP+HTTPS on some device.
>    This shouldn't affect system-wide filtering in any way because it is just extra functionality.
>    May be checking this checkbox triggered reconfiguration of AdGuard, and behaviour had changed.
> 2. Generally, the same proxy should not be set for both HTTP+HTTPS and SOCKS.
>    Typical proxy may be two types - HTTP proxy and SOCKS5 proxy.
>    HTTP proxy is set in macOS settings as system proxy for HTTP+HTTPS (Apple names them as "HTTP proxy" and "HTTPS proxy" but it is incorrect - they are better to be named "HTTP proxy for HTTP" and "HTTP proxy for HTTPS")
>    SOCKS5 proxy is set in macOS settings as system SOCKS5 proxy.
>    So it is better to use only one type of proxy (HTTP+HTTPS or SOCKS)
> 
> However, thousands of requests in the log are generated by Safari, so Safari may be somewhat broken by new filtering method. That's may be just another manifestation of Apple network library incompatibility with Apple NetworkExtensions API, which we are already reported to Apple. Let's wait for Big Sur Beta 10.

It is allowed to set both HTTP and Socks5 proxy in the same port in Clash. There is a specify config called "mixed_port". 

> [https://lancellc.gitbook.io/clash/clash-config-file/general](https://lancellc.gitbook.io/clash/clash-config-file/general)

**Comment by owenzhao** [comment] 2020-10-31 01:48
There is a good news. For macOS Big Sur 11.0.1 beta, when setting HTTP/s Proxy on system Wifi setting with other proxy in LAN. AdGuard now works with ad filtering.

### Steps:
1. Quit Safari.
2. Set HTTP/s Proxy in System Setting. say: 10.0.0.114:7890.
3. Disable and enable AdGuard.
4. Open Safari.

Now AdGuard works. 

However, if the proxy is local,(127.0.0.1:7890), AdGuard still doesn't filter any ads.

AdGuard 2.5.1.913 nightly (CL-1.7.134)
Safari 14.0.1 (16610.2.11.51.4)
macOS Big Sur 11.0.1 Beta版(20B5012d)

**Comment by Chandler-Lu** [comment] 2020-11-13 14:49
我发现在macOS Big Sur 11.0.1，clash (1.30.3.2) 和 adguard 客户端 (2.5.1.918) 的VPN模式好像根本无法共存，不知道楼主有没有找到什么解决方法
-----
I found that the clash and adguard can't work properly at the same time in macOS Big Sur 11.0.1.

**Comment by owenzhao** [comment] 2020-11-14 03:47
> 我发现在macOS Big Sur 11.0.1，clash (1.30.3.2) 和 adguard 客户端 (2.5.1.918) 的VPN模式无法共存，不知道楼主有没有找到什么解决方法
> 
> I found that the clash and adguard can't work properly at the same time in macOS Big Sur 11.0.1. Do you have any solution?

The only way currently is what I mentioned above. Use another computer in your LAN and set "allow other computers in LAN", and set your Mac to use that clashX. In this way, AdGuard would work. 

If that didn't work. Quit Safari and reset AdGuard settings and then try again.

**Comment by Chandler-Lu** [comment] 2020-11-14 10:34
Thanks. This way make it work, but it's too inconvenient. I switched the desktop client to safari extension. :joy:

**Comment by spacexnasa** [comment] 2020-12-23 13:17
> Thanks. This way make it work, but it's too inconvenient. I switched the desktop client to safari extension. 😂
 
socks5 下可以工作，不需要 vpn 模式

**Comment by owenzhao** [comment] 2020-12-28 04:43
> Thanks. This way make it work, but it's too inconvenient. I switched the desktop client to safari extension. 😂

Since macOS 11.1, AdGuard could work alone with other proxy apps like ClashX.

**Closed** 2021-06-02 16:29 UTC
Labels: Question, Wontfix
