### ISSUE TITLE
Huge CPU usage on Apple Silicon

### ISSUE THREAD

**Issue by Peredery** [AdguardTeam/AdguardForMac#1054] opened 2022-03-31 12:28 UTC
### Actual behavior

<details><summary>Screenshot:</summary>

<img width="563" alt="image" src="https://user-images.githubusercontent.com/41237931/161054323-830972a7-c27b-43af-9fd9-84ae699002a6.png">

</details>

### Customer ID 
590873

### Your environment

* Safari

**Comment by Chinaski1** [comment] 2022-03-31 15:26
Hello!

Here is a similar issue to yours. But let's try to figure it out.
https://github.com/AdguardTeam/AdguardForMac/issues/978

Please next time when you find a high CPU load, open the `Activity monitor` -> `Choose AdGuard app` -> Click on [`Sample`](https://uploads.adguard.com/Chinaskidshle.png) -> `Save the sample` -> Send the result to `apple@adguard.com` -> Be advisable if you let us know about the report sent.

Also, logs of the application will be useful:

1. Click **AdGuard icon** in the menu bar --> Gear --> Advanced --> Logging level --> **Debug**;
2. Reproduce the issue and remember the exact time it happened;
3. Menu --> Advanced --> **Export Logs and System Info...**;
4. Send the archive to `apple@adguard.com` and mention this issue number in the subject.

**Comment by Chinaski1** [comment] 2022-05-16 10:45
Any news?

**Comment by Peredery** [comment] 2022-05-16 11:03
Hello, it hasn't happened lately (current version 2.8.1.1140)

**Comment by Chinaski1** [comment] 2022-05-16 11:05
So I close the issue

Reopen it if it reproduces again.

**Comment by Peredery** [comment] 2022-05-17 12:01
@Chinaski1 could you reopen it? :) I got this bug, I'll send a message with samples

**Comment by Chinaski1** [comment] 2022-05-17 12:47
Thank you for the information provided, we got it

**Comment by Chinaski1** [comment] 2022-05-17 13:08
@Peredery 

Unfortunately, the information you have given us does not give us an understanding of the cause of the issue.

1. The log you collected is not debugged.
2. There is no suspicious information in Sample
3. It seems that AdGuard was not filtering the traffic at the time of logging

Would you please try to collect information again?

**Comment by Chinaski1** [comment] 2022-05-17 13:08
@Peredery 

Unfortunately, the information you have given us does not give us an understanding of the cause of the issue.

1. The log you collected is not debugged.
2. There is no suspicious information in Sample
3. It seems that AdGuard was not filtering the traffic at the time of logging

Would you please try to collect information again?

**Comment by rakleed** [comment] 2022-08-02 18:58
.

**Comment by Aydinv13** [comment] 2022-08-24 12:33
There was no any samples/logs received so I'm closing the issue for now. Reopen if needed.

**Closed by Aydinv13** 2022-08-24 12:33 UTC
Labels: P3: Medium, Version: AdGuard v2.9
