### ISSUE TITLE
Adguard desktop not functioning properly in Safari on Sequoia 15.0

### ISSUE THREAD

**Issue by This-is-RTEK** [AdguardTeam/AdguardForMac#1482] opened 2024-09-18 01:30 UTC
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

Version 2.15.1.1731 release

### Browser version

Version 18.0 (20619.1.26.31.6)

### OS version

Sonoma 15.0

### Ad Blocking

AdGuard Base filter

### Privacy

AdGuard Tracking Protection filter, AdGuard URL Tracking filter

### Social

AdGuard Social Media filter

### Annoyances

AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Other Annoyances filter, AdGuard Widgets filter, Adblock Warning Removal List

### Security

Online Malicious URL Blocklist

### Other

AdGuard DNS filter

### Which DNS server do you use?

AdGuard DNS

### DNS protocol

DNS-over-HTTPS

### What Stealth Mode options do you have enabled?

Block trackers, Send Do-Not-Track signals

### Issue Details

Steps to reproduce:
1. updated to Sequoia
(uninstall and reinstall did not resolve issue. problem persists.)
### Expected Behavior

Adguard desktop is failing to operate cosmetic filters on Safari. Firefox is ok.

### Actual Behavior

Adguard only is able to use base DNS filtering on Safari

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

**Comment by Aydinv13** [comment] 2024-09-18 07:57
@igotadell Hi!

Do you have Private Relay enabled? Safari can currently be missing filtering if Private Relay is enabled, so a temporary solution is to disable it until the [problem](https://github.com/AdguardTeam/CoreLibs/issues/1914) is resolved. 
Usually Private Relay is disabled automatically when AdGuard starts, but macOS 15 has changed the behavior.

**Comment by This-is-RTEK** [comment] 2024-09-18 16:34
> @igotadell Hi!
> 
> Do you have Private Relay enabled? Safari can currently be missing filtering if Private Relay is enabled, so a temporary solution is to disable it until the [problem](https://github.com/AdguardTeam/CoreLibs/issues/1914) is resolved. Usually Private Relay is disabled automatically when AdGuard starts, but macOS 15 has changed the behavior.

yes I use private relay. Adguard was completely functional with it on the last version. Will adjust, but I hope Adguard can resolve this. Thank you.

**Comment by This-is-RTEK** [comment] 2024-09-18 16:39
<img width="1680" alt="Screenshot 2024-09-18 at 12 36 24 PM" src="https://github.com/user-attachments/assets/fd4763b8-9334-4388-832c-1063cb413f3a">

Even with PR disabled Adguard is not working as expected in system apps too. This ad box in News wouldn't have been there three days ago.

**Comment by atticusmatticus** [comment] 2024-09-18 17:49
I have the same issue since updating to macOS 15.0 Sequoia. Disabling Private Relay appears to have fixed the issue for me so far. I hope that this will be fixed for Private Relay soon though as it is a complementary feature to a content blocker.

**Comment by Aydinv13** [comment] 2024-09-19 09:23
@igotadell @atticusmatticus 

We'd like to ask you for help, we need remote access to your device because this problem is consistently recurring on your end and that way it'll be easier to find a quick solution. 
If you don't mind, send the connection ID from [AnyDesk](https://anydesk.com/en)(or any other app's ID that is convenient for you) to qa@adguard.com
Thank you in advance!

**Comment by This-is-RTEK** [comment] 2024-09-19 17:37
> @igotadell @atticusmatticus
> 
> We'd like to ask you for help, we need remote access to your device because this problem is consistently recurring on your end and that way it'll be easier to find a quick solution. If you don't mind, send the connection ID from [AnyDesk](https://anydesk.com/en)(or any other app's ID that is convenient for you) to [qa@adguard.com](mailto:qa@adguard.com) Thank you in advance!

I respectfully decline. Surely someone on the dev team has a Mac and can replicate.

**Comment by atticusmatticus** [comment] 2024-09-20 03:12
Unfortunately I am going to have to decline as well. I am happy to send logs etc. if you outline the procedure here. But I am not comfortable giving you unfettered access to my computer.

**Comment by Aydinv13** [comment] 2024-09-20 10:07
The logs would also be helpful, thanks.

<details><summary>Instruction:</summary>

1. Click **AdGuard icon** in the menu bar --> Gear --> Advanced --> Logging --> Logging level --> **Debug**;
2. Reproduce the issue and remember the exact time it happened;
3. Menu --> Advanced --> Logging --> **Export Logs and System Info...**;
4. Send the archive to `qa@adguard.com` and mention this issue number in the subject.
</details>

**Comment by atticusmatticus** [comment] 2024-09-20 15:10
Logs have been sent to the email. Please let me know if there is anything else I can provide.

**Comment by This-is-RTEK** [comment] 2024-09-20 21:42
https://www.bleepingcomputer.com/news/apple/macos-sequoia-change-breaks-networking-for-vpn-antivirus-software/
Other security software is also having trouble, maybe this is related? I'm sure the team will resolve this. I'm willing to bet more Mac users than Windows users pay for your software...

**Comment by sfionov** [comment] 2024-09-23 09:28
mask.icloud.com
mask-h2.icloud.com

**Comment by Aydinv13** [comment] 2024-09-23 09:30
@atticusmatticus thanks for the logs.

Since the [issue](https://github.com/AdguardTeam/CoreLibs/issues/1914) already exists, let's track the process there. I'm closing the current one as a duplicate.

**Closed as completed by Aydinv13** 2024-09-23 09:30 UTC
Labels: Bug, Resolution: Duplicate, Status: Closed, Waiting for data, Priority: P4
