### ISSUE TITLE
Automatically filter applications breaks Flutter

### ISSUE THREAD

**Issue by nohli** [AdguardTeam/AdguardForMac#795] opened 2020-11-30 12:32 UTC
When enabling `Automatically filter applications` in AdGuard Preferences, the commands `flutter pub get` and `flutter pub upgrade` don't work.

Is there a way to whitelist an application?
Flutter, Terminal or Visual Studio Code don't appear in the filtered Applications list.

This error happens for a few weeks. Before it worked without issues.

```
Unhandled exception:
Bad state: Future already completed
#0      _AsyncCompleter.complete (dart:async/future_impl.dart:43:31)
#1      _NativeSocket.startConnect.<anonymous closure>.connectNext.<anonymous closure> (dart:io-patch/socket_patch.dart:678:23)
#2      _NativeSocket.issueWriteEvent.issue (dart:io-patch/socket_patch.dart:1043:14)
#3      _NativeSocket.issueWriteEvent (dart:io-patch/socket_patch.dart:1050:12)
#4      _NativeSocket.multiplex (dart:io-patch/socket_patch.dart:1071:11)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

**Comment by sfionov** [comment] 2020-11-30 12:39
@nohli What OS do you use? Do you use Little Snitch? 

Note that Little Snitch and AdGuard can't work together correctly on Big Sur due to Apple bug. We recommend to use Automatic proxy mode until the problem is fixed.

**Comment by nohli** [comment] 2020-11-30 12:47
> @nohli What OS do you use? Do you use Little Snitch?
> 
> Note that Little Snitch and AdGuard can't work together correctly on Big Sur due to Apple bug. We recommend to use Automatic proxy mode until the problem is resolved.

Thanks, it works in `Automatic Proxy` mode.

Not using Little Snitch though.

macOS Big Sur 11.0.1 (on an Intel Mac)
AdGuard 2.5.1.928 release
(so both latest stable versions)

**Comment by sfionov** [comment] 2020-12-07 08:42
@nohli Do you have another services in "Network Preferences" other than AdGuard and Ethernet/Wi-Fi/Bluetooth?

There may be some anti-virus or network utilities.

**Comment by Chinaski1** [comment] 2020-12-07 10:54
In case you do not use any of the above:

1. Menu -> Gear -> Advanced -> Logging level -> Debug;
2. Reproduce the issue (and remember the exact time when it happened);
3. Menu -> Advanced -> Export Logs and System Info...;
4. Send the archive to **`apple@adguard.com`** and mention this issue number in the subject.

**Comment by nohli** [comment] 2020-12-07 13:40
> @nohli Do you have another services in "Network Preferences" other than AdGuard and Ethernet/Wi-Fi/Bluetooth?
> 
> There may be some anti-virus or network utilities.

![Preferences](https://user-images.githubusercontent.com/43643339/101354779-fa90ac80-3895-11eb-9f51-0955c8b7b06e.jpg)

**Comment by Chinaski1** [comment] 2020-12-07 13:51
- One more user faced a similar issue: **2221267**;
- More information is being clarified at this time;
- Logs are added to NCloud.

**Comment by Chinaski1** [comment] 2020-12-11 11:07
Checked the situation on my side and I can confirm that the issue [is reproducing](https://uploads.adguard.com/Chinaski38mj3.png).
 - Logs are added to NCloud
- Time in Logs 13:58-14:00 | 11.12.2020

**Comment by ngorskikh** [comment] 2020-12-25 08:43
Reported a bug to Apple, discussion: https://developer.apple.com/forums/thread/670163

**Comment by bhtri** [comment] 2021-01-16 06:32
I used to have the same problem, and trying to change `Filtering Mode` to `Automatic Proxy` it seems that the flutter commands (flutter doctor -v, flutter upgrade, flutter pub upgrade, ...) work well without having to disable or disable Adguard.
Refer [here](https://stackoverflow.com/a/65676366/6284714)

**Comment by nohli** [comment] 2021-03-20 06:58
Just checked again. It's not crashing anymore, but it's not working either (maybe because of no internet connection).

**Comment by ameshkov** [comment] 2021-03-22 08:26
Quick update - this is an Apple's bug which they seem to have no intention to fix.

It can also be fixed on the side of Dart, but it looks like they have no idea the bug exists. We'll file an issue to them (or find a relevant one) and close this one then.

**Comment by ameshkov** [comment] 2021-03-22 08:33
Relevant bug report in Dart: https://github.com/dart-lang/sdk/issues/45116

**Closed by ameshkov** 2021-03-22 08:33 UTC

**Comment by aliafshany** [comment] 2025-11-08 09:55
> [@nohli](https://github.com/nohli) What OS do you use? Do you use Little Snitch?
> 
> Note that Little Snitch and AdGuard can't work together correctly on Big Sur due to Apple bug. We recommend to use Automatic proxy mode until the problem is resolved.

@ameshkov 
Sorry to bring this issue up again, but I would like to know if there are still any conflicts with Little Snitch in macOS 26.1 before purchasing it.
Thanks in Advanced.
