### ISSUE TITLE
Add fingerprint confirmation support to AdGuard Installer

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardForMac#833] opened 2021-02-11 14:49 UTC
For now it only works with a password

**Comment by rakleed** [comment] 2021-11-16 21:02
@vozersky isn't this a duplicate of https://github.com/AdguardTeam/AdguardForMac/issues/534?

**Comment by Chinaski1** [comment] 2021-11-17 11:47
Yep, looks like we cant implement this feature :(

**Closed** 2021-11-17 11:47 UTC
Labels: Enhancement, Installer, Resolution: Won't Fix, Status: Resolved, Medium
