### ISSUE TITLE
Adguard will use very high CPU

### ISSUE THREAD

**Issue by zongUMR** [AdguardTeam/AdguardForMac#771] opened 2020-11-12 13:12 UTC
### Steps to reproduce

1.Open Adguard on Mac 
2. Observer the `activity monitor`
3.
4.

### Actual behavior

`mDnsResponder` uses very high CPU, it will be normal if exit Adguard
<img width="1554" alt="Screen Shot 2020-11-12 at 21 08 11" src="https://user-images.githubusercontent.com/11454175/98944072-71eb4e80-252b-11eb-82c2-e85fce3da684.png">

<details><summary>Screenshot:</summary>

</details>

### Your environment

* Environment name and version: (e.g. Chrome 59):
* Any specific potentially conflicting software installed: (e.g. antiviruses, firewalls, traffic counters, cleaners)
<img width="579" alt="Screen Shot 2020-11-12 at 21 11 39" src="https://user-images.githubusercontent.com/11454175/98944214-abbc5500-252b-11eb-9ffa-ef13f717f01a.png">

**Comment by ngorskikh** [comment] 2020-11-12 18:08
@zongUMR hello! Could you try adding `5353` to `network.extensions.eclude.ports` (**AdGuard icon -> Gear icon -> Advanced -> Advanced Settings**)?

**Comment by zongUMR** [comment] 2020-11-13 11:34
![Uploading Screen Shot 2020-11-13 at 19.31.58.png…]()
Unfortunately , it does not work well for this issue
![Uploading Screen Shot 2020-11-13 at 19.32.38.png…]()

**Comment by zongUMR** [comment] 2020-11-13 11:35
it does not solve this problem

**Comment by ngorskikh** [comment] 2020-11-13 14:23
@zongUMR please see if the following helps:
1. Exit AdGuard
2. Open Terminal and execute: 
```
defaults write com.adguard.mac.adguard FilteringProcessesV2 -array-add "<dict><key>bundleId</key><string>com.apple.mDNSResponder</string><key>enabled</key><true/><key>filteringBundleIds</key><array><string>com.apple.mDNSResponder</string></array><key>filteringProcessNames</key><array><string>mDNSResponder</string></array><key>localizedName</key><string>mDNSResponder</string></dict>"
```
3. Open AdGuard again

**Comment by Chinaski1** [comment] 2020-11-16 10:04
Hello @zongUMR 

Any news? :)

**Comment by zongUMR** [comment] 2020-11-16 10:11
Unfortunately , it does not work for me :(,

**Comment by Chinaski1** [comment] 2020-11-16 10:47
I tried during the last week to "catch" a similar issue, but failed to do so.

Looks like you faced some kind of rare bug on the new OS.

Please clarify whether you use third-party soft by type of antivirus or VPN services?

**Comment by Chinaski1** [comment] 2020-11-19 13:19
I am closing this task as we have not been able to reproduce this issue.

If the user provides additional information or an issue happens with someone else, we will re-open it.

**Closed** 2020-11-19 13:19 UTC
