### ISSUE TITLE
Something corrupting traffic in Chrome

### ISSUE THREAD

**Issue by planet0** [AdguardTeam/AdguardForMac#544] opened 2019-06-25 11:38 UTC
### Steps to reproduce

1. Visit https://github.com/AdguardTeam/AdguardHome/issues/
2. Click on an issue
3. Click on the 'Issues' tab
4. Repeat multiple times until behaviour

### Expected behavior
Browsing is as per usual

### Actual behavior

The webpage code is corrupted. Quit or disable AdGuard and issue won't occur.

<details><summary>Screenshot:</summary>

<img width="1552" alt="github" src="https://user-images.githubusercontent.com/46271764/60095217-6dd15c00-9791-11e9-806e-dfdc9f5b6c05.png">

</details>

### Your environment

* Environment name and version: (e.g. Chrome 59): Chrome Version 75.0.3770.90 (Official Build) (64-bit)
* Any specific potentially conflicting software installed: (e.g. antiviruses, firewalls, traffic counters, cleaners) AdGuard Home

**Comment by sfionov** [comment] 2019-06-25 11:41
Duplicate of https://github.com/AdguardTeam/CoreLibs/issues/951

**Comment by sfionov** [comment] 2019-06-25 11:44
@planet0 Thank you for instructions to reproduce. However, closing this because issue is already in CoreLibs.

**Closed by sfionov** 2019-06-25 11:44 UTC

**Comment by planet0** [comment] 2019-06-25 11:54
No problem @sfionov!

**Comment by planet0** [comment] 2019-07-10 11:35
Fixed as of 2.1.0.568 nightly. 👍🏼
