### ISSUE TITLE
Cannot complete the installation on macOS 15

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardForMac#1481] opened 2024-09-17 23:19 UTC
### Please answer the following questions for yourself before submitting a question.

- [X] I am running the latest version
- [X] I checked to make sure that this issue has not already been filed

### Ask a question

There is no "Allow" button appear in Privacy and Security on macOS 15. How to resolve it?
<img width="912" alt="Screenshot 2024-09-18 at 7 13 39 AM" src="https://github.com/user-attachments/assets/59e208c8-62af-4732-a23f-fdfeead7c414">
<img width="827" alt="Screenshot 2024-09-18 at 7 17 32 AM" src="https://github.com/user-attachments/assets/a10f1856-b98d-48f7-b63a-f9259e7ac3d8">

**Comment by legion-heresy** [comment] 2024-09-18 05:46
This setting has been moved to System Settings > General > Login Items and Extensions > Network Extensions

**Comment by ghost** [comment] 2024-09-18 06:01
> This setting has been moved to System Settings > General > Login Items and Extensions > Network Extensions

Thanks! Apple hides it so hard.

**Comment by Aydinv13** [comment] 2024-09-18 07:48
It will be fixed in the upcoming release. Duplicate of https://github.com/AdguardTeam/AdguardForMac/issues/1434

**Closed as completed by Aydinv13** 2024-09-18 07:48 UTC
Labels: Question, Resolution: Duplicate, Status: Closed, Priority: P4
