### ISSUE TITLE
The behavior of viewing the original certificate through the browser extension is not always consistent.

### ISSUE THREAD

**Issue by ZeroClover** [AdguardTeam/AdguardForMac#836] opened 2021-02-18 06:08 UTC
### Steps to reproduce
1. Visit an HTTPS site and turn on AdGuard HTTPS filtering.
2. Use the browser extension to view the original certificate

### Expected behavior

Completion of the certificate chain can be displayed each time.

### Actual behavior

Most of the time, no certificate chain is provided, only the final entity certificate.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/13190004/108312864-4777f400-71f2-11eb-9a0a-53d9302756fe.png)

![image](https://user-images.githubusercontent.com/13190004/108312887-4fd02f00-71f2-11eb-9b31-d21cfbd228a5.png)

</details>

### Customer ID 

No autoresponder email was received.

### Your environment
macOS 11.2.1
AdGuard for Mac 2.5.1.928 setapp (CL-1.7.150)
Also tested on non-Setapp versions
AdGuard Assistant 1.1.1

**Comment by ZeroClover** [comment] 2021-02-18 06:12
PS: When using AdGuard on Windows(native Windows applications, not through the HTTP proxy for macOS AdGuard.), the full certificate chain can always be viewed through the browser extension.

**Comment by ameshkov** [comment] 2021-02-18 10:24
Hmm, the code is almost identical, I wonder what's wrong.

**Comment by ameshkov** [comment] 2021-02-18 10:26
Another strange thing is that I cannot reproduce this (at least not on the NextDNS website).

@sfionov when can we store only the leaf cert?

**Comment by sfionov** [comment] 2021-02-18 10:42
@ameshkov Only leaf cert is stored in db. 

I was able to reproduce it. On first try full chain was displayed, from second try chain is not displayed. 
Restarting AdGuard helps, but only for the first try. From second try chain is not displayed again.

**Comment by ameshkov** [comment] 2021-02-18 10:46
@sfionov ah, so it's a CL issue? Can we store the full chain w/o the CA cert?

**Comment by sfionov** [comment] 2021-02-18 10:48
I think it is UI issue :(

**Comment by sfionov** [comment] 2021-02-18 11:24
I was able to reproduce it with Keychain Access :)

1) Open Keychain Access
2) Select some certificate
2) Open Menu -> Certificate Assistant -> Evaluate...
3) Press Next
4) Press "Show certificate..." button - chain is shown
5) Press Close
6) Press "Show certificate..." again - chain is not shown

Looks like another Big Sur bug 🎉 

![image](https://user-images.githubusercontent.com/47204/108350203-01705f80-71f5-11eb-80ce-7bddc04bb1da.png)

**Comment by ameshkov** [comment] 2021-02-18 11:28
Yeah, nothing like that on Catalina

**Comment by sfionov** [comment] 2021-02-18 12:04
Reported to Apple, Feedback ID: FB9009475

**Comment by evasilis** [comment] 2021-03-21 12:32
Nothing like that on 11.2.3

![Screen Shot 2021-03-21 at 2 28 24 PM](https://user-images.githubusercontent.com/74712901/111905025-4be23780-8a52-11eb-9e45-ff06d59eb802.png)

**Comment by ameshkov** [comment] 2021-03-21 14:19
@sfionov @Stillness-2 guys, could you please check it on our side just in case and close this if it was fixed.

**Comment by ZeroClover** [comment] 2021-03-21 14:24
@ameshkov The problem still exists on Macs with Intel chips or Apple Silicon (macOS 11.2.3) and has not been fixed by Apple.

![image](https://user-images.githubusercontent.com/13190004/111908405-19f1c500-8a94-11eb-99c2-5848b14b78be.png)


I don't think @evasilis has followed all the steps to reproduce the problem.

**Comment by ameshkov** [comment] 2021-03-21 14:26
@ZeroClover thanks for checking it!

**Closed** 2021-12-21 15:54 UTC
Labels: Bug, P4: Low, Resolution: Fixed, Status: Resolved, macOS Bug, Version: AdGuard v2.7

**Comment by sfionov** [comment] 2023-03-31 14:48
JFYI: Apple bug that triggered this problem was finally fixed in macOS 13.3.
