### ISSUE TITLE
"Need your permission" screen won't go away

### ISSUE THREAD

**Issue by HenryQW** [AdguardTeam/AdguardForMac#844] opened 2021-03-09 15:46 UTC
### Steps to reproduce
1. Update to 2.5.3.955 release (CL-1.7.200)
2. Launch AdGuard

### Expected behavior
No screen popup

### Actual behavior
A screen popup requesting permission, but permission was already granted for previous version and there is no option for granting it again.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/5896343/110497243-2ff3a300-80ee-11eb-9ef8-e53175863d78.png)

![image](https://user-images.githubusercontent.com/5896343/110497422-5580ac80-80ee-11eb-914d-24c499522b7b.png)

</details>

### Customer ID 
3024699

### Your environment
![image](https://user-images.githubusercontent.com/5896343/110497664-92e53a00-80ee-11eb-91c2-254a0b53142a.png)

**Comment by Chinaski1** [comment] 2021-03-09 15:55
Hello there!

The application seems to think for some reason that it needs permission to create a kernel extension.

Please tell me, does filtering work correctly or are ads not filtered?

**Comment by HenryQW** [comment] 2021-03-09 17:14
@Chinaski1 No it doesn't work. Any way to revert to a previous build for the moment?

**Comment by Chinaski1** [comment] 2021-03-10 10:47
The error appears to have occurred when the kernel extension was created. It is unlikely to be product version dependent.

I can suggest the following to solve the issue:

#### Totally reinstall the app

- Remove `/Library/Application Support/com.adguard.mac.adguard`
- Remove `~/Library/Preferences/com.adguard.mac.adguard.plist`
- Remove `~/Library/Group Containers/TC3Q7MAJXF.com.adguard.com`
- Remove app file from Applications
- Install the app from the direct link (agrd.io/mac)

####  If this method doesn't help

1) From the Apple menu select Restart.
2) As your Mac restarts, press and hold down the Command(⌘) + R keys immediately upon hearing the startup chime. Hold the keys until the Apple logo appears to get the computer in Recovery mode.
3) The computer is now in Recovery mode. From the Apple menu select Utilities -> Terminal
4) Run the command: `csrutil disable`
5) From the Apple menu, select Restart.
6) After the macOS is loaded, open terminal and type commands:

`sudo kextcache -invalidate /`
`sudo kextcache -invalidate /Library/Application\ Support/com.adguard.Adguard/kext/com.adguard.nfext.kext`
`sudo kextcache --clear-staging`
`sudo chflags -R restricted /Library/StagedExtensions`

1) From the Apple menu, select Restart.
2) As your Mac restarts, press and hold down the Command(⌘) + R keys immediately upon hearing the startup chime. Hold  the keys until the Apple logo appears to get the computer in Recovery mode.
3) The computer is now in Recovery mode. From the Apple menu select Utilities -> Terminal
4) Run the command: `csrutil enable`
5) From the Apple menu, select Restart.
6) Now your kext should run..

**Comment by HenryQW** [comment] 2021-03-10 15:01
Hi @Chinaski1 , I have tried a total reinstallation and it didn't help.

![image](https://user-images.githubusercontent.com/5896343/110649123-38f97880-81b1-11eb-9032-c72de61140ea.png)


The MacBook is jamf managed I could not enter the recovery mode, and couldn't try the kextcache method.

**Comment by Chinaski1** [comment] 2021-03-10 15:39
Hmm....also you can try to open `Terminal` and type:
- `kextstat` Is `com.adguard.nfext` there?
- If `NO` try to type `sudo /sbin/kextload -v 6 /Library/Application\ Support/com.adguard.mac.adguard/kext/com.adguard.nfext.kext/`

**Comment by Chinaski1** [comment] 2021-03-10 16:50
I tried searching for similar information on the `Jamf` forum and came across this feedback from one of the users. Perhaps this might help. It's Sophos, but I think the kext principle is similar to AdGuard.

`The only way I got it working properly is to base the Sophos installation on a smart group that checks that the kext list already exists. Once the approved list is present on the Mac first; the Sophos installtion works properly.`

**Comment by akmLaVx** [comment] 2021-03-18 18:13
received logs: 2959950

**Comment by HenryQW** [comment] 2021-03-20 03:23
My company IT team says there is no restriction(from jamf) on kernel extensions. They also refused to add AdGuard to their "trustworthy list".

**Comment by Aydinv13** [comment] 2021-03-22 08:28
If the issue still persists you may change to Big Sur (there is no kernel extension). It should help

**Comment by HenryQW** [comment] 2021-03-22 11:22
I wish I could (I told them that), Big Sur is not yet on their approved list, such a headache.

**Comment by Chinaski1** [comment] 2021-03-30 09:39
Since this issue is caused by peculiarity of the operating system, I am closing this task.
Reopen it if necessary.

**Closed** 2021-03-30 09:40 UTC
