### ISSUE TITLE
Support macOS Big Sur

### ISSUE THREAD

**Issue by Jax0rz** [AdguardTeam/AdguardForMac#713] opened 2020-06-23 15:15 UTC
Please add support to [macOS Big Sur](https://www.apple.com/macos/big-sur-preview/)

**Comment by zzebrum** [comment] 2020-06-25 13:12
@Jax0rz related to #692

**Comment by zzebrum** [comment] 2020-06-29 13:12
By the way, I've updated to Big Sur (v11.0 Beta 20A4299v) just today and it seems that you can allow kernel extensions: 
https://uploads.adguard.com/Screenshot_2020-06-29_at_11.54.09_2020-06-29_16-09-47.png
https://uploads.adguard.com/Screenshot_2020-06-29_at_11.53.11_2020-06-29_16-09-57.png

**Comment by Jax0rz** [comment] 2020-06-29 13:42
> By the way, I've updated to Big Sur (v11.0 Beta 20A4299v) just today and it seems that you can allow kernel extensions:
> https://uploads.adguard.com/Screenshot_2020-06-29_at_11.54.09_2020-06-29_16-09-47.png
> https://uploads.adguard.com/Screenshot_2020-06-29_at_11.53.11_2020-06-29_16-09-57.png

Where can we download the latest nightly(beta) version?

**Comment by Jax0rz** [comment] 2020-06-29 13:52
> By the way, I've updated to Big Sur (v11.0 Beta 20A4299v) just today and it seems that you can allow kernel extensions:
> https://uploads.adguard.com/Screenshot_2020-06-29_at_11.54.09_2020-06-29_16-09-47.png
> https://uploads.adguard.com/Screenshot_2020-06-29_at_11.53.11_2020-06-29_16-09-57.png

It doesn't work.you have to reboot your computer after allow kernel extension, but you can't allow the kernel extension after reboot.

**Comment by zzebrum** [comment] 2020-06-29 13:54
@Jax0rz yay, it asked for system restart and AdGuard has been working after that :(

**Comment by ezrazw** [comment] 2020-07-01 02:55
@Jax0rz  Tried multiple times by following your introduction, it still did not work for me.

**Comment by ezrazw** [comment] 2020-07-01 02:56
@zzebrum Tried multiple times by following your introduction, it still did not work for me.

**Comment by Greigh** [comment] 2020-07-03 17:39
@zzebrum I can confirm that AdGuard's Kernel extensions don't work even after Restart. Could it be possible that this is a Big Sur/Apple bug and not an AdGuard bug?

**Comment by abhilash0505** [comment] 2020-07-06 08:58
A lot of apps that use kext have been broken. I rebooted using recovery mode and ran _spctl kext-conset add <TEAMID>_ for some extensions and they also don't seem to work. I get a popup with the list of 3rd party extensions and macOS requests for a restart. Once I restart, the loop of request, restart goes on.

**Comment by zzebrum** [comment] 2020-07-06 12:59
honestly, I don't know why it is working for me 👀 I only allowed kext as the system asked and nothing else

Did anyone try to disable SIP?

**Comment by Greigh** [comment] 2020-07-06 22:46
@zzebrum I just disabled SIP and I am still having the same issue.

**Comment by Greigh** [comment] 2020-07-06 23:04
<img width="881" alt="Screen Shot 2020-07-06 at 7 03 10 PM" src="https://user-images.githubusercontent.com/57759540/86663159-6f944900-bfbb-11ea-8bfd-d92de83bd847.png">

**Comment by Greigh** [comment] 2020-07-06 23:38
Even tried to run it as a SU in Terminal. Here's the Terminal log: https://ghostbin.co/paste/wuamb

**Comment by BrokenHope** [comment] 2020-07-07 18:43
Can someone test with beta 2 if you can enable Adguard on Big Sur.

**Comment by ezrazw** [comment] 2020-07-07 18:55
> Can someone test with beta 2 if you can enable Adguard on Big Sur.
After updating to beta 2, Adguard still does not work.

**Comment by Greigh** [comment] 2020-07-07 19:00
I definitely will when I get home in 90mins or so.

**Comment by pytrisss** [comment] 2020-07-07 19:15
> Can someone test with beta 2 if you can enable Adguard on Big Sur.
> After updating to beta 2, Adguard still does not work.

Yep. Even manual load via kextutil does nothing sadly.
Console shows:
error	21:00:17.695945+0200	syspolicyd	Kernel Extension BLOCKED: Kext (TC3Q7MAJXF, com.adguard.nfext) version: 22a034ab43e1927fd235ca6af95a675761d72bc7

But the kext won't show up in the security settings to check.
So I went to recovery and did
`/usr/sbin/spctl kext-consent add TC3Q7MAJXF`

On the next reboot, adguard kext showed in the list for user consent and after the next reboot it shows as loaded.
So far this fixes it for me.

**Comment by ezrazw** [comment] 2020-07-07 20:02
@pytrisss, thanks. After executing the same command you mentioned in terminal, ADGUARD also works for me now.

**Comment by Greigh** [comment] 2020-07-07 20:13
Even without using that command, I do not have any issues with Big Sur beta 2. Maybe because I have SIP off. But I'm not going to mess with it.

**Comment by bermudalocket** [comment] 2020-07-19 17:39
Anyone have an update? Unfortunately manually loading/trusting the kext doesn't work on my machine :-(

**Comment by Greigh** [comment] 2020-07-19 17:41
> Anyone have an update? Unfortunately manually loading/trusting the kext doesn't work on my machine :-(

Go into recovery mode and manually consent to the Kext by running this command `/usr/sbin/spctl kext-consent add TC3Q7MAJXF`. This has worked for me on several macOS computers.

**Comment by abhilash0505** [comment] 2020-07-20 09:12
Hi folks, I ran `csrutil disable` in recovery mode. Upon restart, the System Preferences -> Security had AdGuard listed and I enabled and restarted again. AdGuard works totally fine now. Beware: the command is used to disable SIP. Read about SIP [here](https://support.apple.com/en-us/HT204899).

**Comment by ameshkov** [comment] 2020-07-20 11:35
@zzebrum let's update milestones properly.

We're working on the system extension for a long time already, there should be an issue where we show the current status AND where we explain what are the possible alternatives.

**Comment by zzebrum** [comment] 2020-07-20 12:52
closed as dup #692

**Closed by zzebrum** 2020-07-20 12:52 UTC
Labels: Compatibility, Enhancement, P1: Critical

**Comment by zzebrum** [comment] 2020-07-23 12:57
new nightly is out! details are here: https://github.com/AdguardTeam/AdguardForMac/issues/692#issuecomment-662970815
