### ISSUE TITLE
System extensions support in Big Sur

### ISSUE THREAD

**Issue by iDjay** [AdguardTeam/AdguardForMac#692] opened 2020-03-24 18:50 UTC
After updating to 10.15.4 I received an information window about AdGuard being incompatible with future OS versions, here's more about it:
https://support.apple.com/en-us/HT210999

_____________________________________________________________
_**Status update on the task and a temporary solution is [here](https://github.com/AdguardTeam/AdguardForMac/issues/692#issuecomment-661017730) 👇 .**_

**Comment by Antediluvian** [comment] 2020-03-25 00:51
Yep, same as me here, waiting for the update.

**Comment by sh2sg** [comment] 2020-03-25 02:35
AdGuard is using kernel extension, Apple is going to drop kernel extension support, so unless AdGuard is rewriting the software, or else it will become useless like those legacy Safari extensions. 

Is there any timeline when the new AdGuard will be out? Will the performance drop or improve comparing with using kernel extension?

**Comment by zzebrum** [comment] 2020-03-25 07:45
AdGuard version compatible with the new Mac OS is scheduled for this spring. No worries, please! :)

**Comment by planet0** [comment] 2020-03-25 22:23
Just adding a +1 that I got the same message, with the same URL.
https://support.apple.com/en-au/HT210999

<img width="532" alt="Screen Shot 2020-03-26 at 9 22 14 am" src="https://user-images.githubusercontent.com/46271764/77591154-7d115000-6f43-11ea-8afa-97b704bbe697.png">

**Comment by xiaoleigithub** [comment] 2020-03-26 01:58
期待

**Comment by planet0** [comment] 2020-04-04 01:28
https://adguard.com/en/blog/kernel-extensions-deprecation.html

> [...]we're already working on it and we'll almost assuredly have finished the job by the time of macOS 10.16 release. In fact, judging from Apple's statement to developers, it looks like you'll be able to allow apps with old APIs run on 10.16 anyway, it just won't happen by default.

**Comment by Jax0rz** [comment] 2020-06-29 07:22
> https://adguard.com/en/blog/kernel-extensions-deprecation.html
> 
> > [...] we're already working on it and we'll almost assuredly have finished the job by the time of macOS 10.16 release. In fact, judging from Apple's statement to developers, it looks like you'll be able to allow apps with old APIs run on 10.16 anyway, it just won't happen by default.

Any alpha release ? I'm a big fan of your app and I can't wait to use your app in macOS 11

**Comment by zzebrum** [comment] 2020-07-20 12:49
1. The issue is assigned to the v2.5 which should be released before macOS v11.
2. The first nightly version with System extension support expected this week 🤞 it will be available [here](https://agrd.io/mac_nightly).
3. In some cases, AdGuard v2.4 with kernel extension support is working on Big Sur beta 2 without any problems. A temporary solution is [to disable SIP](https://www.imore.com/how-turn-system-integrity-protection-macos) and then allow kernel extension in Security and Privacy in system setting. 

> _Note: disabling SIP may not help, other solutions may be found here: #713_

**Comment by zzebrum** [comment] 2020-07-23 12:10
guys, the new nightly v2.5.0.838 is available now! 🎈 🤞 
If you are already on a nightly channel, just check for updates from the app. Otherwise, [download](https://agrd.io/mac_nightly) and install new version manually.

If something goes unexpected, collect debug log and send it to apple[at]adguard[dot]com so we could react faster.

**Comment by pytrisss** [comment] 2020-07-23 12:19
> guys, the new nightly v2.5.0.838 is available now! 🎈 🤞
> If you are already on a nightly channel, just check for updates from the app. Otherwise, [download](https://agrd.io/mac_nightly) and install new version manually.
> 
> If something goes unexpected, collect debug log and send it to apple[at]adguard[dot]com so we could react faster.

Thanks! Installed and works great so far. I noticed it creates a VPN configuration. Will there be any documentation explaining how this works please?

**Comment by zzebrum** [comment] 2020-07-23 12:59
@pytrisss I guess we can do that. Any particular questions?

**Comment by pytrisss** [comment] 2020-07-23 13:14
@zzebrum Well I guess this is the change that solves the kext issue so I would like to know what is the traffic flow.
I don't understand the inner workings of adguard enought to make wild guesses but I could imagine you dump all traffic through the tunnel and catch the relevant flows of http/https. That could mean you could screen all traffic on the computer and not just the traffic that is from the monitored browser apps. (Maybe you could've already done this before with kext)
Or I got it completely wrong and that's why I would love some simple "We take this, push it through here and out the other end comes a web without ads".
Doesn't have to be right now but would be nice some time in the future before the final release 💯

**Comment by A1saka** [comment] 2020-07-24 10:31
@zzebrum New version works well, but it created a VPN configuration, that make conflicts with other apps which need to use VPN, any solutions? Other filtering mode can't be chosen.

**Comment by sfionov** [comment] 2020-07-25 13:31
@A1saka New filtering mode is shown as "VPN" in system settings (that's Apple requirement) but uses socket-level filtering, not packet-level tunneling. Most of VPNs are packet tunnels, and should not conflict with new AdGuard filtering. If your VPN does not work with new filtering mode, please report to us, we will take a look.

**Comment by Hackl0us** [comment] 2020-07-27 02:44
> @A1saka New filtering mode is shown as "VPN" in system settings (that's Apple requirement) but uses socket-level filtering, not packet-level tunneling. Most of VPNs are packet tunnels, and should not conflict with new AdGuard filtering. If your VPN does not work with new filtering mode, please report to us, we will take a look.

Thank you so much for the amazing work on supporting macOS Big Sur 11.0. Just like you said, I have to use the proxy tool called [Surge](https://nssurge.com) most of the time due to special network conditions.

I could see that the latest AdGuard Nightly build creates a VPN, while Surge will modify current Network Proxy Settings (HTTP Proxy / HTTPS Proxy / Socks5 Proxy),  which will cause a conflict. If I enable Surge, AdGuard won't filter any ads. If I disable Surge, AdGuard works well but I cannot access the internet.

This won't happen if I use Kernel Extension mode. I think it is still possible to use Kernel Extension mode in macOS Big Sur, all I need to do is to temporarily disable the SIP in Recovery mode (`csrutil disable`), reboot and let AdGuard register the kernel extension, then reenable the SIP, it will work.

However, in the latest Nightly Build, AdGuard doesn't let me to choose the mode. So now, I have to use AdGuard Safari extension...

**Comment by sfionov** [comment] 2020-07-27 06:39
> I could see that the latest AdGuard Nightly build creates a VPN, while Surge will modify current Network Proxy Settings (HTTP Proxy / HTTPS Proxy / Socks5 Proxy), which will cause a conflict. 

Actually, it should not cause a conflict. AdGuard should filter system proxies in both kext and network extension modes.
Task to track this: https://github.com/AdguardTeam/CoreLibs/issues/1322

**Comment by ZeroClover** [comment] 2020-09-01 13:18
> Actually, it should not cause a conflict. AdGuard should filter system proxies in both kext and network extension modes.

@sfionov In Kext mode AdGuard works well, but in Network Extension mode, once the System Proxy is enabled, AdGuard will not work.

If other NE software is also enabled in Network Extension mode, macOS will be disconnected.

**Comment by sfionov** [comment] 2020-09-01 13:37
@ZeroClover 

> @sfionov In Kext mode AdGuard works well, but in Network Extension mode, once the System Proxy is enabled, AdGuard will not work.

Yep, and AdguardTeam/CoreLibs#1322 is about this issue.

> If other NE software is also enabled in Network Extension mode, macOS will be disconnected.

If your VPN doesn't work together with AdGuard in NE mode, please let us know, we will try to reproduce and fix it.

Limitation about one running VPN in macOS is for packet tunnels (typical VPN is packet tunnel)
But AdGuard use socket-level filtering, so it is "transparent proxy" in terms of NE. MacOS doesn't turn off transparent proxies when packet tunnel is running.

**Comment by sfionov** [comment] 2020-09-01 13:47
@ZeroClover I personally use Wireguard + AdGuard now, and both of them work together
![image](https://user-images.githubusercontent.com/47204/91859070-ad87b380-ec72-11ea-8c36-5f1f0966fa3f.png)

**Comment by ZeroClover** [comment] 2020-09-01 13:50
> If your VPN doesn't work together with AdGuard in NE mode, please let us know, we will try to reproduce and fix it.

@sfionov I'm using Surge. Millions of users (macOS / iOS) in mainland China use this software (mainly to bypass censorship).

You can download it from here: https://nssurge.com (This is commercial software, but offers a 14-day free trial.)

Surge also uses Network Extension to create a TUN device, and the developers have recently released a white paper explaining how the software works, which I think may help.

https://manual.nssurge.com/book/understanding-surge/en/

**Comment by sfionov** [comment] 2020-09-01 13:57
Thank you very much for information! We'll check this.

Also, some compatibility issues with other transparent proxying apps may be fixed by adding outbound proxy support to AdGuard for Mac (as you suggested in another issue).

**Comment by ZeroClover** [comment] 2020-09-01 14:36
@sfionov After talking with the author @Dreamacro of [Clash](https://github.com/Dreamacro/clash), I may know the cause of this problem.

(Clash provides similar functionality to Surge, and it's open-source software)

Clash uses the TUN implementation of WireGuard, but in order to take over network traffic, both Clash and Surge add global routing tables, whereas your WireGuard may only add routing tables for WG intranet IPs.

![image](https://user-images.githubusercontent.com/13190004/91864966-754c9900-eca3-11ea-8c98-e6183ab888d3.png)

**Comment by sfionov** [comment] 2020-09-01 14:46
@ZeroClover But basically it is the same as that WireGuard do - adds some specific routes instead of default route. However, we'll take a look to a difference.

**Comment by A1saka** [comment] 2020-09-02 02:31
@sfionov @ZeroClover Hi, New nightly beta version(2.5.0.849 nightly) work well with Surge by Kernel Mode on macOS Big Sur 11 Beta 5. Both Surge and Adguard work fine. Thanks for your wonderful job, really appreciate that.

**Comment by ZeroClover** [comment] 2020-09-02 02:34
@A1saka In fact, Kext mode can always be used with Surge.

However, macOS 11 Big Sur requires you to enter `csrutil enable --without kext `in recovery mode in order to use AdGuard Kext mode, which may not be easy for most users.

**Closed** 2020-10-12 16:01 UTC
Labels: Compatibility, P1: Critical, Resolution: Done, Status: Resolved

**Comment by HoweChen** [comment] 2020-11-13 13:47
Is there a solution to make adguard work with proxifier??

**Comment by A1saka** [comment] 2020-11-14 01:04
@HoweChen 
[Adguard](https://kb.adguard.com/en/macos/solving-problems/big-sur-issues)
 I hope it can help.

**Comment by HoweChen** [comment] 2020-11-17 14:45
> @HoweChen
> [Adguard](https://kb.adguard.com/en/macos/solving-problems/big-sur-issues)
> I hope it can help.

Thanks for helping. I've already found this one but the thing is that every time I want to make proxifier and adguard work together, the OS crashes. Maybe I should wait for the fix from either of the aps..
