### ISSUE TITLE
Moose app won't launch

### ISSUE THREAD

**Issue by Rakleed** [AdguardTeam/AdguardForMac#792] opened 2020-11-29 22:04 UTC
### Steps to reproduce
1. Setup [moose app](https://getmoose.in)
2. Open moose app

### Expected behavior
The application launches and works.

### Actual behavior
An error appears while launching the application.

<details><summary>Screenshot:</summary>

![Снимок экрана 2020-11-30 в 00 49 40](https://user-images.githubusercontent.com/19418601/100554601-bbb39300-32a6-11eb-802c-e39d3eda5899.png)

</details>

### Customer ID 
939612

### Your environment

* Environment name and version: macOS 11.0.1, moose 0.6.2
* Any specific potentially conflicting software installed:

**Comment by zzebrum** [comment] 2020-11-30 16:27
@Rakleed a few questions:
- do you use the little snitch app?
- does the moose app added to the filtering apps list?

**Comment by Rakleed** [comment] 2020-11-30 16:39
* I don't know what you mean, but I am using the [AdGuard app for macOS](https://adguard.com/adguard-mac/overview.html).
* No, but if I manually add the application to this list, then the error goes away.

**Comment by zzebrum** [comment] 2020-12-01 12:28
@Rakleed you also need to file a bug report in the [moose repo](https://github.com/ritz078/moose/issues). 
Do you have any antivirus apps installed? Also, did you have this problem with macOS Catalina?

**Comment by Rakleed** [comment] 2020-12-02 13:40
> @Rakleed you also need to file a bug report in the [moose repo](https://github.com/ritz078/moose/issues).

Should I write about the incompatibility between AdGuard and moose?

> Do you have any antivirus apps installed? Also, did you have this problem with macOS Catalina?

No. I can't check on Catalina, because I only have Big Sur.

**Comment by zzebrum** [comment] 2020-12-02 17:26
@Rakleed  I can't reproduce the issue on my side 
And the other things are that 1) we do not filter multicast and 2) the error appears when the app is **not** added to the filtered application list. 

> Should I write about the incompatibility between AdGuard and moose?

Yep, we would be very grateful if the moose devs will take a look into the error.

**Comment by Chinaski1** [comment] 2020-12-07 09:14
I Can't reproduce the issue regardless of the OS.
And the application works no matter if it is added to the filtered list.
It seems that the issue is still a local one.
I am closing this task, if you get a reply from the Moose app developers, please let us know (at support@adguard.com).

**Closed by Chinaski1** 2020-12-07 09:14 UTC
