### ISSUE TITLE
AdGuard icon doesn't show correctly

### ISSUE THREAD

**Issue by Chinaski1** [AdguardTeam/AdguardForMac#613] opened 2019-10-09 13:45 UTC
# Steps to reproduce

1. Update to the latest version of Catalina.
2. Turn "automatic" in the theme settings.
3. Look at the AdGuard icon on the operating panel.
 It remains clickable and the functions work fine, but the icon is not displayed.

### Your environment

* System info: Catalina 10.15
* AdGuard: 2.1.3.611

**Comment by zzebrum** [comment] 2019-10-10 08:43
closed as a duplicate of #527

**Closed by zzebrum** 2019-10-10 08:43 UTC
Labels: Duplicate
