### ISSUE TITLE
Grammarly Self-Diagnostic Tests are failing on macOS Big Sur 11.0 Public Beta (20A5343j)

### ISSUE THREAD

**Issue by yasithab** [AdguardTeam/AdguardForMac#721] opened 2020-08-10 13:02 UTC
### Steps to reproduce

1. Run [**Grammarly Self-Diagnostic Tests**](https://app.grammarly.com/diagnostic-test?origin=editor) on Safari.

### Expected behavior

Grammarly should pass its **Self-Diagnostic Tests**.

### Actual behavior

Grammarly **Self-Diagnostic Tests** are failing when the AdGuard is running.

<details><summary>Screenshot:</summary>

<img width="1337" alt="AdGuard" src="https://user-images.githubusercontent.com/9078175/89783446-943c8d00-db34-11ea-874a-0eb20212c0de.png">
<img width="1595" alt="BigSur" src="https://user-images.githubusercontent.com/9078175/89783454-969ee700-db34-11ea-9111-d288f47b58d0.png">
<img width="545" alt="Ticket" src="https://user-images.githubusercontent.com/9078175/89784810-ef6f7f00-db36-11ea-95b9-69920aaedef7.png">

</details>

### Customer ID 

As you mentioned, I tried to create a support ticket, but I did not get any reply. May be it is another bug (Please check the screenshot).

### Your environment

* Environment name and version: AdGuard 2.5.0.838 nightly (CL-1.7.2) on macOS Big Sur 11.0 Public Beta (20A5343j) and Safari 14.0 (16610.1.23.1.3)
* Any specific potentially conflicting software installed: Viscosity VPN 1.8.6 (1546), Bitdefender Antivirus for Mac 8.1.6.3, Little Snitch 5.0 preview (6112)

**Comment by adgkart** [comment] 2020-08-14 09:28
Hi! Could you please close all specific potentially conflicting software installed: Viscosity VPN 1.8.6 (1546), Bitdefender Antivirus for Mac 8.1.6.3, Little Snitch 5.0 preview (6112), and try to reproduce this issue again with only AdGuard running?

**Comment by yasithab** [comment] 2020-08-14 09:36
Hello, I closed Viscosity VPN, turned off Little Snitch and Bitdefender, but results are still the same. Please check the attachment.

![Screenshot 2020-08-14 at 15 04 42](https://user-images.githubusercontent.com/9078175/90235910-ac1b5600-de3f-11ea-97d3-99ef251a0ef8.png)

**Comment by zzebrum** [comment] 2020-08-17 13:59
@yasithab is Stealth mode enabled in AdGuard settings?

**Comment by yasithab** [comment] 2020-08-17 16:08
@zzebrum No, it is disabled.

<img width="589" alt="Screenshot 2020-08-17 at 21 37 30" src="https://user-images.githubusercontent.com/9078175/90417864-f0be2000-e0d1-11ea-9168-a567bed88e92.png">
<img width="435" alt="Screenshot 2020-08-17 at 21 37 43" src="https://user-images.githubusercontent.com/9078175/90417868-f287e380-e0d1-11ea-966c-373f1d2176a8.png">

**Comment by zzebrum** [comment] 2020-08-18 08:23
@yasithab please, check with all filters disabled in AdGuard settings too. 
Anyway, I suggest we wait until major problems will be fixed in the next nightly versions of AdGuard. The current version with a new filtering mode for macOS Big Sur is very buggy.

**Comment by Chinaski1** [comment] 2020-10-06 12:01
Hello, @yasithab 

Latest test for BigSur 11.0 Beta (20A5384c)/Safari Browser Version 14.0.1 (16610.2.6.1.6)/AdGuard version: 2.5.0.896 nightly (CL-1.7.116) shows that everything [works correctly](https://uploads.adguard.com/Chinaskiphawu.png).

 This is why I have closed this task.
Let us know if the problem is the issue relevant.

**Closed by Chinaski1** 2020-10-06 12:01 UTC
Labels: Bug
