### ISSUE TITLE
netbiosd (process) starts using a lot of CPU when pausing AdGuard

### ISSUE THREAD

**Issue by dave-holland** [AdguardTeam/AdguardForMac#937] opened 2021-09-16 15:38 UTC
### Steps to reproduce

1. Pause AdGuard

### Expected behavior

netbiosd should not start to consume a lot of CPU.

### Actual behavior

netbiosd starts to consume a lot of CPU.

<details><summary>Screenshot:</summary>

<video src="https://user-images.githubusercontent.com/90854657/133640511-29916f36-a2c7-4187-b56c-cd385a9c1b6f.mov"></video>

(https://user-images.githubusercontent.com/90854657/133640511-29916f36-a2c7-4187-b56c-cd385a9c1b6f.mov)

<video src="https://user-images.githubusercontent.com/90854657/133640564-d9ec05ec-e394-4f0c-96a4-a6341e63851c.mov"></video>

(https://user-images.githubusercontent.com/90854657/133640564-d9ec05ec-e394-4f0c-96a4-a6341e63851c.mov)

</details>

You can see from the screen recording that the % CPU of netbiosd was about 0 before I pause AdGuard. Then exactly when AdGuard is paused, the % CPU jumps up. Enabling AdGuard again doesn't make it go down. Killing the netbiosd process doesn't work.

### Customer ID 

The Support Request ticket number is 537027.

### Your environment

* Environment name and version: 
  * macOS 12 beta 6 (Build 21A5506j)
  * AdGuard for Mac 2.6.0.1022 nightly (CL-1.8.183, DNS-1.6.36)

**Comment by Chinaski1** [comment] 2021-09-16 16:03
Hello!

At the first glance, this is the same issue as AdguardTeam/CoreLibs#1436

**Comment by ameshkov** [comment] 2021-09-16 16:05
Yeah, that's definitely it. We should probably rename that original issue in CL since this is a MacOS bug.

**Comment by sfionov** [comment] 2021-09-16 16:07
This case is different - netbiosd consumes CPU while AG protection is not running.

And that task is about consuming CPU while network extension in running, and apps immediately stops consuming CPU after network-extension is stopped.

**Comment by ameshkov** [comment] 2021-09-16 16:09
Ah yeah, you're right, that one is indeed different. Can we reproduce it on our side?

Also, could it be that when the network extension is unloaded the sockets are also closed incorrectly, just like how they're closed when it's loaded?

**Comment by dave-holland** [comment] 2021-09-21 18:58
The issue seems to have been resolved in macOS 12 beta 7 (Build 21A5522h)

**Comment by cryptopatik22** [comment] 2022-09-15 16:32
Hey guys, the issue seems to be back. As far as I can tell, it is the same exact problem. Version of AdGuard - v2.9.0.1166 beta.

**Comment by cryptopatik22** [comment] 2022-09-15 16:34
Do I have to create a new issue?

**Comment by sfionov** [comment] 2022-09-26 06:16
@cryptopatik22 No, reopened this one.

**Closed** 2023-04-18 15:12 UTC
Labels: P3: Medium, Resolution: Fixed, Status: Resolved, Version: AdGuard Backlog

**Comment by sfionov** [comment] 2023-07-13 10:59
@antonreshetov I wonder why Apple did not fix it yet, since they agree with presence of this bug even of their forums. As a workaround, if you doesn't need it, you may run `killall -STOP netbiosd` in the Terminal.

**Comment by antonreshetov** [comment] 2023-07-14 05:15
@sfionov Thanks, I'll try

**Comment by antonreshetov** [comment] 2023-08-14 11:52
@sfionov `killall -STOP netbiosd` did not help, the process is restarting again.

**Comment by eSavior** [comment] 2023-11-06 13:50
The following MacRumors thread which links to the following Apple Support instructions should help disable netbiosd so you can get on with your life when you want to pause AdGuard. This bug had bitten me in the past, and my workaround then was to unpause AdGuard. Now, my workaround is to disable netbiosd since I don't need it running on my Mac (running Monterey 12.6.5)

--

MacRumors thread:
https://forums.macrumors.com/threads/netbiosd-high-cpu-usage-on-m1-monterey.2335812/

Apple support reconfiguration instructions:
https://support.apple.com/en-gb/102050
