### ISSUE TITLE
Non latin language in AdGuard nightly 2.5.2.939 and Big Sur 10.11.1

### ISSUE THREAD

**Issue by evasilis** [AdguardTeam/AdguardForMac#812] opened 2021-01-17 10:33 UTC
Typing using Greek in facebook messenger, produces garbage. Turning adguard off corrects this behaviour

![Screen Shot 2021-01-17 at 11 39 21](https://user-images.githubusercontent.com/74712901/104837863-2143f900-58c0-11eb-994b-a14978fdd587.png)

**Comment by Chinaski1** [comment] 2021-01-18 09:55
Duplicate of https://github.com/AdguardTeam/AdguardForMac/issues/813
You can follow the progress of the solution in this task.

**Closed** 2021-01-18 09:55 UTC

**Comment by Chinaski1** [comment] 2021-01-18 10:15
@evasilis 

Hello there!

I try to reproduce that issue but messages in Greek are sent without any issues.

Could you please specify the list of filters used?

**Comment by Chinaski1** [comment] 2021-01-18 11:13
Please clarify the model of your Mac, is it Apple Silicon?

**Comment by evasilis** [comment] 2021-01-18 11:17
Hi and thanks for your reply!

It is a 5.1 (intel) 12core macpro running big sur.
