### ISSUE TITLE
Adguard slows chrome down considerably 

### ISSUE THREAD

**Issue by HenryQW** [AdguardTeam/AdguardForMac#779] opened 2020-11-15 18:10 UTC
### Steps to reproduce

1. Enable automatically filter applications under Network tab in Adguard
2. Use chrome to browser websites, the loading speed is slowed down for many websites, some took minutes to load
3. Safari is not affected

### Expected behavior
Webpages are loaded instantly

### Actual behavior
Webpages take minutes to load

A video demo: https://youtu.be/sP4VdX2qwbc

### Customer ID 
3024699

### Your environment
* Environment name and version: Chrome 87.0.4280.60, macOS Big Sur 11.0.1.
* Any specific potentially conflicting software installed: None

**Comment by Chinaski1** [comment] 2020-11-16 09:00
Hello there!

To troubleshoot this issue, we need to get the app logs.

Here's what we need you to do:

1. Menu -> Gear -> Advanced -> Logging level -> Debug;
2. Reproduce the issue (and remember the exact time when it happened);
3. Menu -> Advanced -> Export Logs and System Info...;
4. Send the archive to **`apple@adguard.com`** and mention this issue number in the subject.

**Comment by WorldIRC** [comment] 2020-11-17 20:50
https://github.com/AdguardTeam/AdguardFilters/issues/66533

Experiencing the issues since Chrome 87 beta.  Reverted to 86 and issues went away, but now that 87 is out, issues are back.  See my report for more details.

**Comment by WorldIRC** [comment] 2020-11-17 21:21
I've switched to the AdGuard Chrome Extension for now, seems OK.  Looks like AdGuard for Mac is the issue.

**Comment by ameshkov** [comment] 2020-11-17 22:49
merged into https://github.com/AdguardTeam/CoreLibs/issues/1374

**Closed** 2020-11-17 22:52 UTC
Labels: Duplicate
